{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 26458,
          "sha512": "7f37e3448af8c11bc518bd027fab1ba9376bf22af01cf61f56e7b1de948221e0eaeb8397de12c45d746e52f0adef1132bff2be32ac343a33f88111e0011032cf",
          "sha256": "bd692a3306973a2ea848e1a019bef20774497fe2cd8dbb5b87279912cf193f60",
          "sha1": "3622e445bcc1eced94383645bb8a25fbf92ad36b",
          "md5": "3860375bb88d68530a711dc3c0cbd066"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 26458,
          "sha512": "7f37e3448af8c11bc518bd027fab1ba9376bf22af01cf61f56e7b1de948221e0eaeb8397de12c45d746e52f0adef1132bff2be32ac343a33f88111e0011032cf",
          "sha256": "bd692a3306973a2ea848e1a019bef20774497fe2cd8dbb5b87279912cf193f60",
          "sha1": "3622e445bcc1eced94383645bb8a25fbf92ad36b",
          "md5": "3860375bb88d68530a711dc3c0cbd066"
        }
      ]
    }
  ]
}
