{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 50204,
          "sha512": "907a892270d34d183810883cd0868534af2e13d1f2a94c094eb72e8a9413998f214dca51ca77d0d952dc774a8bb6bed42dfd0bfcb4b7c5a391c8b69729367f1c",
          "sha256": "598842c89d02253e90714f309f0913fafdcfbebf3a6f2f7fd18b921cb10ea9f6",
          "sha1": "c0071ad801613e8d0925606e24c149cfe30fd17c",
          "md5": "931d407d95d51674ac0ca99618783342"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 50204,
          "sha512": "907a892270d34d183810883cd0868534af2e13d1f2a94c094eb72e8a9413998f214dca51ca77d0d952dc774a8bb6bed42dfd0bfcb4b7c5a391c8b69729367f1c",
          "sha256": "598842c89d02253e90714f309f0913fafdcfbebf3a6f2f7fd18b921cb10ea9f6",
          "sha1": "c0071ad801613e8d0925606e24c149cfe30fd17c",
          "md5": "931d407d95d51674ac0ca99618783342"
        }
      ]
    }
  ]
}
