{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 50115,
          "sha512": "dc4f375e901db0861b643be4bb52af321456f60e3ecd874d6046d9f099861335e4bbfd1673220cf1977cbc0ceac07522f456e787449743080377f0256b108fe7",
          "sha256": "9e4c449e24734f615a6d6851d8dfbb53db17b80e99be6dfaab86417f0ac4b96f",
          "sha1": "314df1936fe7c248c8f68268b42fd6a0263db95c",
          "md5": "0e326c629d819ab907d67023ffa09635"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 50115,
          "sha512": "dc4f375e901db0861b643be4bb52af321456f60e3ecd874d6046d9f099861335e4bbfd1673220cf1977cbc0ceac07522f456e787449743080377f0256b108fe7",
          "sha256": "9e4c449e24734f615a6d6851d8dfbb53db17b80e99be6dfaab86417f0ac4b96f",
          "sha1": "314df1936fe7c248c8f68268b42fd6a0263db95c",
          "md5": "0e326c629d819ab907d67023ffa09635"
        }
      ]
    }
  ]
}
