{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 10428,
          "sha512": "6847c744a1de9159db3aeac556245f58831ccc9107bfc4909f38734eb6c106d5d244c46830631c8ab7f615799190146599a3f89dfc408ec40691667f5b9c65cf",
          "sha256": "64d5e272b512e1b7460237692ef96977932a377b534f56e462ce8ea3510cae48",
          "sha1": "843581d532afbd242f681a5f7fbb991ec71dd5f8",
          "md5": "a7de37557fb97a208ccf87748d67e5be"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 10428,
          "sha512": "6847c744a1de9159db3aeac556245f58831ccc9107bfc4909f38734eb6c106d5d244c46830631c8ab7f615799190146599a3f89dfc408ec40691667f5b9c65cf",
          "sha256": "64d5e272b512e1b7460237692ef96977932a377b534f56e462ce8ea3510cae48",
          "sha1": "843581d532afbd242f681a5f7fbb991ec71dd5f8",
          "md5": "a7de37557fb97a208ccf87748d67e5be"
        }
      ]
    }
  ]
}
