{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_safe_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_profile-1.0.aar",
          "url": "open_file_safe_profile-1.0.aar",
          "size": 13753,
          "sha512": "6942f3eb706766a25d586709d0ab237c4110ffcd4fe0a2e7b2ee0f622df4e84d8ed672300237f5bd1f3ce609e535e9a7f874d1c885cb41bdf60e90b23a2188ff",
          "sha256": "73cad81936fccfd9492e5f4a5d0bf200752b5e8a0091bf9de82988d452e607a0",
          "sha1": "dc785cf888d3336d33e126daf0e2dd4a6263e416",
          "md5": "039c141a3cb6b6d6b83b7bc9b2158096"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_profile-1.0.aar",
          "url": "open_file_safe_profile-1.0.aar",
          "size": 13753,
          "sha512": "6942f3eb706766a25d586709d0ab237c4110ffcd4fe0a2e7b2ee0f622df4e84d8ed672300237f5bd1f3ce609e535e9a7f874d1c885cb41bdf60e90b23a2188ff",
          "sha256": "73cad81936fccfd9492e5f4a5d0bf200752b5e8a0091bf9de82988d452e607a0",
          "sha1": "dc785cf888d3336d33e126daf0e2dd4a6263e416",
          "md5": "039c141a3cb6b6d6b83b7bc9b2158096"
        }
      ]
    }
  ]
}
