{
  "formatVersion": "1.1",
  "component": {
    "group": "appmire.be.flutterjailbreakdetection",
    "module": "flutter_jailbreak_detection",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection-1.0-debug.aar",
          "url": "flutter_jailbreak_detection-1.0-debug.aar",
          "size": 7555,
          "sha512": "13715d10541af30142c9db620ca62589c77bea85205e5cdca9d83308928d9edc67073354688ea7aa4c7e7b6e5f77e663ce2c76b0d353cf87541f797c01ade6fb",
          "sha256": "8e07155c656fafa2d461fc1767ea622c67ec9c5004267840a02eb656697777ea",
          "sha1": "87140ccba9ddca857a900d0d0c534ef42742a2f6",
          "md5": "4c1798a4155374ee967e24548927500b"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection-1.0-debug.aar",
          "url": "flutter_jailbreak_detection-1.0-debug.aar",
          "size": 7555,
          "sha512": "13715d10541af30142c9db620ca62589c77bea85205e5cdca9d83308928d9edc67073354688ea7aa4c7e7b6e5f77e663ce2c76b0d353cf87541f797c01ade6fb",
          "sha256": "8e07155c656fafa2d461fc1767ea622c67ec9c5004267840a02eb656697777ea",
          "sha1": "87140ccba9ddca857a900d0d0c534ef42742a2f6",
          "md5": "4c1798a4155374ee967e24548927500b"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection-1.0-release.aar",
          "url": "flutter_jailbreak_detection-1.0-release.aar",
          "size": 7337,
          "sha512": "87ae7e7c85b304e04f144cf2a724583643a171076b0b557df5c51a1da95650e91f480ea037fe3a12f54d8cfbc6707ce09a5e53798628eb08ba3afd04c9779802",
          "sha256": "92b2410caede6751380b9eb400c934773ada00c5e9b895394c50b12c4585791e",
          "sha1": "bdc8edd97cb0657ce312154c62f0bb62858e3121",
          "md5": "f95fff0ede8bd4a9f4b9ccf324bad34e"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection-1.0-release.aar",
          "url": "flutter_jailbreak_detection-1.0-release.aar",
          "size": 7337,
          "sha512": "87ae7e7c85b304e04f144cf2a724583643a171076b0b557df5c51a1da95650e91f480ea037fe3a12f54d8cfbc6707ce09a5e53798628eb08ba3afd04c9779802",
          "sha256": "92b2410caede6751380b9eb400c934773ada00c5e9b895394c50b12c4585791e",
          "sha1": "bdc8edd97cb0657ce312154c62f0bb62858e3121",
          "md5": "f95fff0ede8bd4a9f4b9ccf324bad34e"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection-1.0-profile.aar",
          "url": "flutter_jailbreak_detection-1.0-profile.aar",
          "size": 7339,
          "sha512": "c9e73a6f3e0a0dc178ad10a93e2df5b64ede3ccf097a0523c1f1e6a0c2d0f968cb3e46a2e7330d6108857a06d01a115955dd321a77f00660f9190a35ec8538e2",
          "sha256": "6b5157761866bce8b2802bd9faa6ba116925ed822e6dc6d2051dded5940ca844",
          "sha1": "8a07d86951c63a34eca4f6d6d411f6cc7902e0d7",
          "md5": "be807d864603632583ca9f4c54639f05"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection-1.0-profile.aar",
          "url": "flutter_jailbreak_detection-1.0-profile.aar",
          "size": 7339,
          "sha512": "c9e73a6f3e0a0dc178ad10a93e2df5b64ede3ccf097a0523c1f1e6a0c2d0f968cb3e46a2e7330d6108857a06d01a115955dd321a77f00660f9190a35ec8538e2",
          "sha256": "6b5157761866bce8b2802bd9faa6ba116925ed822e6dc6d2051dded5940ca844",
          "sha1": "8a07d86951c63a34eca4f6d6d411f6cc7902e0d7",
          "md5": "be807d864603632583ca9f4c54639f05"
        }
      ]
    }
  ]
}
