{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 6842,
          "sha512": "d5a30944cec200e736ac24001e084334cfc7438ac71fefb2ba18d6aeccc198a4fec05e3527b13073bcd3f2620703f4864a57b6ed18f0b52400c59205823f8080",
          "sha256": "b5cd74f77ad056ad44181360810c8efc962f0a3708aa13c8aa7689c71955f055",
          "sha1": "475cead67b6f346a967c3acc2b77803349b20d3f",
          "md5": "74376f0eea0edf7e3fcf93fbb07dd626"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 6842,
          "sha512": "d5a30944cec200e736ac24001e084334cfc7438ac71fefb2ba18d6aeccc198a4fec05e3527b13073bcd3f2620703f4864a57b6ed18f0b52400c59205823f8080",
          "sha256": "b5cd74f77ad056ad44181360810c8efc962f0a3708aa13c8aa7689c71955f055",
          "sha1": "475cead67b6f346a967c3acc2b77803349b20d3f",
          "md5": "74376f0eea0edf7e3fcf93fbb07dd626"
        }
      ]
    }
  ]
}
