{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9333,
          "sha512": "a301dfe6dad86f85a337a90cb3c79a7337c65ed7777ae4de8dec54bad68c0717d34224fd4027aa02c0bfddfd6a0a131087a29d05a4ac7a912181ac9937de59d3",
          "sha256": "d312d772681bd2b4b4e740a11b3df4e415f7b0157e959781f37c290d2a0fe373",
          "sha1": "a3cc35ea6cd9a4335293b4630fc72401d629fc53",
          "md5": "00da169b85242c1856e3c2ee73c64583"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9333,
          "sha512": "a301dfe6dad86f85a337a90cb3c79a7337c65ed7777ae4de8dec54bad68c0717d34224fd4027aa02c0bfddfd6a0a131087a29d05a4ac7a912181ac9937de59d3",
          "sha256": "d312d772681bd2b4b4e740a11b3df4e415f7b0157e959781f37c290d2a0fe373",
          "sha1": "a3cc35ea6cd9a4335293b4630fc72401d629fc53",
          "md5": "00da169b85242c1856e3c2ee73c64583"
        }
      ]
    }
  ]
}
