{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 9990,
          "sha512": "0306ff5fc60fd2e43a45da583a4f85a479b559a49e887ea217ddb469b6e95f695df7e600cbb63799d5e00c3bcd5a8bfe70bde397b283474ff4d2147c4fa87ced",
          "sha256": "7abba0219e9ba37be54372995889e592a1c14cd8b8340ea52cf7c64610ed3dc5",
          "sha1": "5f25d66315742a3b36f42281619029df2aefab77",
          "md5": "7c64a7f4b118cea3e9732a5ad222dbfc"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 9990,
          "sha512": "0306ff5fc60fd2e43a45da583a4f85a479b559a49e887ea217ddb469b6e95f695df7e600cbb63799d5e00c3bcd5a8bfe70bde397b283474ff4d2147c4fa87ced",
          "sha256": "7abba0219e9ba37be54372995889e592a1c14cd8b8340ea52cf7c64610ed3dc5",
          "sha1": "5f25d66315742a3b36f42281619029df2aefab77",
          "md5": "7c64a7f4b118cea3e9732a5ad222dbfc"
        }
      ]
    }
  ]
}
