{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.0-debug.aar",
          "url": "package_info_plus-1.0-debug.aar",
          "size": 7978,
          "sha512": "9b17450778294c9accabb92f9e95f99e3a9bfe80684764edccfa35f1594ebd27e9eb4807f474e996d13d985a6f7e1fdfbcc7af0f28cd9fa796e4b1d921c310d5",
          "sha256": "0f079f8a0e0c3de49b9f59ef16ec7f6009ae12e7fd1b2c5ebebe7bc7ce6d9a4e",
          "sha1": "715eb199af04401fea8c7b87113c6584c2d8fe92",
          "md5": "2d10349f03df5827e5b2d013a1c23081"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.0-debug.aar",
          "url": "package_info_plus-1.0-debug.aar",
          "size": 7978,
          "sha512": "9b17450778294c9accabb92f9e95f99e3a9bfe80684764edccfa35f1594ebd27e9eb4807f474e996d13d985a6f7e1fdfbcc7af0f28cd9fa796e4b1d921c310d5",
          "sha256": "0f079f8a0e0c3de49b9f59ef16ec7f6009ae12e7fd1b2c5ebebe7bc7ce6d9a4e",
          "sha1": "715eb199af04401fea8c7b87113c6584c2d8fe92",
          "md5": "2d10349f03df5827e5b2d013a1c23081"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.0-release.aar",
          "url": "package_info_plus-1.0-release.aar",
          "size": 7680,
          "sha512": "75bf053d1ec611f0b84ec708d494e2c38dd1172347859c2b2556abb8191c1ababfabd7c0d071a98657a619a9bd05dffcc41fa576c897648f23648bd3d442f088",
          "sha256": "7846302c373f0c09c0013a0421cc686cc4aba1cd58f12e48267861d8a1f385ad",
          "sha1": "7bfbca8a79024f6cd5ba3ed342024dd10297a10d",
          "md5": "488502c301a2f47ef018e1821561729c"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.0-release.aar",
          "url": "package_info_plus-1.0-release.aar",
          "size": 7680,
          "sha512": "75bf053d1ec611f0b84ec708d494e2c38dd1172347859c2b2556abb8191c1ababfabd7c0d071a98657a619a9bd05dffcc41fa576c897648f23648bd3d442f088",
          "sha256": "7846302c373f0c09c0013a0421cc686cc4aba1cd58f12e48267861d8a1f385ad",
          "sha1": "7bfbca8a79024f6cd5ba3ed342024dd10297a10d",
          "md5": "488502c301a2f47ef018e1821561729c"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.0-profile.aar",
          "url": "package_info_plus-1.0-profile.aar",
          "size": 7676,
          "sha512": "5281dc194071b6d28cd41a55c507b2a0637b9d02fec0fda4475089b72c2f7eb779aacccc518c00bed28b213acdee81ffeea80ccdc2694a66b88bd6bb5b2b591b",
          "sha256": "85fee7285c7fd2cade21848ce10f510671d15f4748d46a0942b8d9545efa0524",
          "sha1": "0003b655d7aaf204e62b75a0ac53282b93efa908",
          "md5": "3ba82efce289813e8d7c2649049c62e1"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.0-profile.aar",
          "url": "package_info_plus-1.0-profile.aar",
          "size": 7676,
          "sha512": "5281dc194071b6d28cd41a55c507b2a0637b9d02fec0fda4475089b72c2f7eb779aacccc518c00bed28b213acdee81ffeea80ccdc2694a66b88bd6bb5b2b591b",
          "sha256": "85fee7285c7fd2cade21848ce10f510671d15f4748d46a0942b8d9545efa0524",
          "sha1": "0003b655d7aaf204e62b75a0ac53282b93efa908",
          "md5": "3ba82efce289813e8d7c2649049c62e1"
        }
      ]
    }
  ]
}
