{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer-1.0-debug.aar",
          "url": "syncfusion_flutter_pdfviewer-1.0-debug.aar",
          "size": 10388,
          "sha512": "7bd28688a94486ff8caea743de00255fb462587412bde18f97cacbc726b429524ac75a36a983822f94874d2f6f1e1a312550d9c4ce47140dbf5e7d8cf98fb119",
          "sha256": "4da2e2a093e6720ae7e1a1b31ce23ec3066696ef643f0bfe08ce2d1fb2937d2e",
          "sha1": "393749571a7b3f97dfd7051a6eede6e6f2fa6aae",
          "md5": "f3714a03f7b76042190e380280e175e9"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer-1.0-debug.aar",
          "url": "syncfusion_flutter_pdfviewer-1.0-debug.aar",
          "size": 10388,
          "sha512": "7bd28688a94486ff8caea743de00255fb462587412bde18f97cacbc726b429524ac75a36a983822f94874d2f6f1e1a312550d9c4ce47140dbf5e7d8cf98fb119",
          "sha256": "4da2e2a093e6720ae7e1a1b31ce23ec3066696ef643f0bfe08ce2d1fb2937d2e",
          "sha1": "393749571a7b3f97dfd7051a6eede6e6f2fa6aae",
          "md5": "f3714a03f7b76042190e380280e175e9"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer-1.0-release.aar",
          "url": "syncfusion_flutter_pdfviewer-1.0-release.aar",
          "size": 9971,
          "sha512": "7732bf8a3e3af9f1692263d539999abc2ef522534063063a011b214efdb39f8cf2fe33fd1e050d3decd5b0d8ef4ae6a784d9974ed2e888128e3c52c833a9bb42",
          "sha256": "ac5d978c3be096c8dcebe32d82b000750b986390d3daf045b2749848357d4070",
          "sha1": "24ea164b0e418e94a240874412400b87964527d5",
          "md5": "c84a7f0dedb33e9ee75e7bf13c73747a"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer-1.0-release.aar",
          "url": "syncfusion_flutter_pdfviewer-1.0-release.aar",
          "size": 9971,
          "sha512": "7732bf8a3e3af9f1692263d539999abc2ef522534063063a011b214efdb39f8cf2fe33fd1e050d3decd5b0d8ef4ae6a784d9974ed2e888128e3c52c833a9bb42",
          "sha256": "ac5d978c3be096c8dcebe32d82b000750b986390d3daf045b2749848357d4070",
          "sha1": "24ea164b0e418e94a240874412400b87964527d5",
          "md5": "c84a7f0dedb33e9ee75e7bf13c73747a"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer-1.0-profile.aar",
          "url": "syncfusion_flutter_pdfviewer-1.0-profile.aar",
          "size": 9970,
          "sha512": "772d9281881f12afdad5bd4d0322755469e5e7a0b5a803a6d9606f86c114835d0f686bc6cfac769327ae827d7f964349ceb2d834dab404b4791a6c12cb89baa8",
          "sha256": "2663581fc0713a8c7295da267d35837eb4e124c80543caf3812a2ca082db0652",
          "sha1": "642857be891256ab9cfcdd0c7fb73a036cded5f2",
          "md5": "858cd1dd4cc0ab3489bf882a8d54245f"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer-1.0-profile.aar",
          "url": "syncfusion_flutter_pdfviewer-1.0-profile.aar",
          "size": 9970,
          "sha512": "772d9281881f12afdad5bd4d0322755469e5e7a0b5a803a6d9606f86c114835d0f686bc6cfac769327ae827d7f964349ceb2d834dab404b4791a6c12cb89baa8",
          "sha256": "2663581fc0713a8c7295da267d35837eb4e124c80543caf3812a2ca082db0652",
          "sha1": "642857be891256ab9cfcdd0c7fb73a036cded5f2",
          "md5": "858cd1dd4cc0ab3489bf882a8d54245f"
        }
      ]
    }
  ]
}
