{
  "formatVersion": "1.1",
  "component": {
    "group": "appmire.be.flutterjailbreakdetection",
    "module": "flutter_jailbreak_detection_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_profile-1.0.aar",
          "url": "flutter_jailbreak_detection_profile-1.0.aar",
          "size": 7339,
          "sha512": "c9e73a6f3e0a0dc178ad10a93e2df5b64ede3ccf097a0523c1f1e6a0c2d0f968cb3e46a2e7330d6108857a06d01a115955dd321a77f00660f9190a35ec8538e2",
          "sha256": "6b5157761866bce8b2802bd9faa6ba116925ed822e6dc6d2051dded5940ca844",
          "sha1": "8a07d86951c63a34eca4f6d6d411f6cc7902e0d7",
          "md5": "be807d864603632583ca9f4c54639f05"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_profile-1.0.aar",
          "url": "flutter_jailbreak_detection_profile-1.0.aar",
          "size": 7339,
          "sha512": "c9e73a6f3e0a0dc178ad10a93e2df5b64ede3ccf097a0523c1f1e6a0c2d0f968cb3e46a2e7330d6108857a06d01a115955dd321a77f00660f9190a35ec8538e2",
          "sha256": "6b5157761866bce8b2802bd9faa6ba116925ed822e6dc6d2051dded5940ca844",
          "sha1": "8a07d86951c63a34eca4f6d6d411f6cc7902e0d7",
          "md5": "be807d864603632583ca9f4c54639f05"
        }
      ]
    }
  ]
}
