{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "size": 4676,
          "sha512": "be4f3722eeb92a5213423fa37e1aaaefccbc5bac898f97db4bcc42c174bc70ac7cc0f63ab8592a3fb5259598a92ff9411606009f60ffe9fd36eaafc65efe2969",
          "sha256": "8443cacf6cc93b51c9de876a5100c2cce3c160a092a1b5a5c4712d3bdf563ce4",
          "sha1": "e2219feb23f4b0a9e9ecbe6c918078508d035715",
          "md5": "72441e9162a56aa2ec7bfb947150d2e4"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "size": 4676,
          "sha512": "be4f3722eeb92a5213423fa37e1aaaefccbc5bac898f97db4bcc42c174bc70ac7cc0f63ab8592a3fb5259598a92ff9411606009f60ffe9fd36eaafc65efe2969",
          "sha256": "8443cacf6cc93b51c9de876a5100c2cce3c160a092a1b5a5c4712d3bdf563ce4",
          "sha1": "e2219feb23f4b0a9e9ecbe6c918078508d035715",
          "md5": "72441e9162a56aa2ec7bfb947150d2e4"
        }
      ]
    }
  ]
}
