{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27759,
          "sha512": "dbc784f4c567e9b43c8a6646733f403cd94af0bc4ee0bdda2f42b52e7f206e7305b1a5359d383e7f799c9abb42ad1ad05f9627cf7afbbd62e3413cf281954cb0",
          "sha256": "286a284464b8166c8f98d54b3f317ef0fca3f3b54dfc26981b251322422bc2d8",
          "sha1": "36e159f5d6d472c20e2cfeb6a506720eb1b6496d",
          "md5": "f8b504f2f13ca56029e9e8e722121142"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27759,
          "sha512": "dbc784f4c567e9b43c8a6646733f403cd94af0bc4ee0bdda2f42b52e7f206e7305b1a5359d383e7f799c9abb42ad1ad05f9627cf7afbbd62e3413cf281954cb0",
          "sha256": "286a284464b8166c8f98d54b3f317ef0fca3f3b54dfc26981b251322422bc2d8",
          "sha1": "36e159f5d6d472c20e2cfeb6a506720eb1b6496d",
          "md5": "f8b504f2f13ca56029e9e8e722121142"
        }
      ]
    }
  ]
}
