{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27430,
          "sha512": "1ff23f0883416197e509961a4cbfe02f21fbeb33536ed49defbd4baefd4a477bd8ca8e71455cf45ab175bfad981a7bca597f9fd50fbaacb9f68ed1126c872c52",
          "sha256": "a6ab71e98f646329aae65b18f54ef1e0208a961a9de90cd2da64af8555ba2f3c",
          "sha1": "3a283263119c37572a27a59806f525c8cff6478d",
          "md5": "fe3057400c0760c731f831473e39eb84"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27430,
          "sha512": "1ff23f0883416197e509961a4cbfe02f21fbeb33536ed49defbd4baefd4a477bd8ca8e71455cf45ab175bfad981a7bca597f9fd50fbaacb9f68ed1126c872c52",
          "sha256": "a6ab71e98f646329aae65b18f54ef1e0208a961a9de90cd2da64af8555ba2f3c",
          "sha1": "3a283263119c37572a27a59806f525c8cff6478d",
          "md5": "fe3057400c0760c731f831473e39eb84"
        }
      ]
    }
  ]
}
