{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-debug.aar",
          "url": "webview_flutter_android-1.0-debug.aar",
          "size": 112837,
          "sha512": "1091715c7b93dd700966c7dca1ea766ab9f8752c945408ef5630838ce7a3a359e635c0c5d1677770c3440f0a57a9166a18a62d37c963ee76a430f66c38216b59",
          "sha256": "a2b10001f3ce84d6aee9713285c7fda544a8e7a60716cf211b1213772691d8ad",
          "sha1": "9aece607f67172aa54926628668b84016fec2118",
          "md5": "164796e72d92f9b20a34559f5d280e18"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-debug.aar",
          "url": "webview_flutter_android-1.0-debug.aar",
          "size": 112837,
          "sha512": "1091715c7b93dd700966c7dca1ea766ab9f8752c945408ef5630838ce7a3a359e635c0c5d1677770c3440f0a57a9166a18a62d37c963ee76a430f66c38216b59",
          "sha256": "a2b10001f3ce84d6aee9713285c7fda544a8e7a60716cf211b1213772691d8ad",
          "sha1": "9aece607f67172aa54926628668b84016fec2118",
          "md5": "164796e72d92f9b20a34559f5d280e18"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-release.aar",
          "url": "webview_flutter_android-1.0-release.aar",
          "size": 106183,
          "sha512": "4c04d48bbecbb7e7495665dc002aa371f396493871164d8cd28671699512bde0c8d23e1d0cd895189828d4b20c66bbb7b508c394c973d403c6c8baae49da3482",
          "sha256": "70b95fb4ec1ceff29b111bd70e47f86723e792fdfdda78e04689e4f032a3b758",
          "sha1": "89aed0a12e37cf7fc412273e8f29e59b7cfe0c79",
          "md5": "8b2320581edfc0bc5c9b5ad1bfa5f1b0"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-release.aar",
          "url": "webview_flutter_android-1.0-release.aar",
          "size": 106183,
          "sha512": "4c04d48bbecbb7e7495665dc002aa371f396493871164d8cd28671699512bde0c8d23e1d0cd895189828d4b20c66bbb7b508c394c973d403c6c8baae49da3482",
          "sha256": "70b95fb4ec1ceff29b111bd70e47f86723e792fdfdda78e04689e4f032a3b758",
          "sha1": "89aed0a12e37cf7fc412273e8f29e59b7cfe0c79",
          "md5": "8b2320581edfc0bc5c9b5ad1bfa5f1b0"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-profile.aar",
          "url": "webview_flutter_android-1.0-profile.aar",
          "size": 106180,
          "sha512": "1394b998b8595d7189dc074fa57b5199937590370165b9e1c099d0ea494a4952bb447b581980ddebb3b669d057f5c2534abe20251319eff0b36afb9e592cac88",
          "sha256": "2c00ceba81f861135f728356e5667b76dc6ea4cee9e6f1c62e523b79c57e0f21",
          "sha1": "d8129711d598004fee160eca08a7a3d8b1f3c47c",
          "md5": "4eda622c59d6d05077067ee970cf2ca5"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-profile.aar",
          "url": "webview_flutter_android-1.0-profile.aar",
          "size": 106180,
          "sha512": "1394b998b8595d7189dc074fa57b5199937590370165b9e1c099d0ea494a4952bb447b581980ddebb3b669d057f5c2534abe20251319eff0b36afb9e592cac88",
          "sha256": "2c00ceba81f861135f728356e5667b76dc6ea4cee9e6f1c62e523b79c57e0f21",
          "sha1": "d8129711d598004fee160eca08a7a3d8b1f3c47c",
          "md5": "4eda622c59d6d05077067ee970cf2ca5"
        }
      ]
    }
  ]
}
