{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-1.0.aar",
          "url": "connectivity_plus_debug-1.0.aar",
          "size": 9326,
          "sha512": "0603196a7cd0185da377b3611853b67fa0132cbb59f5d3944e78a347dba252c09ac7673305498fe66755769afeec1d8e1159d0ea8cfeedff9bf262944bf268b5",
          "sha256": "89ebf5dbd137924a2d9938a9125cd055fad8ad23e3d2df857f1122e2cd2e6efa",
          "sha1": "a52b41b9c9e1c24742d30a9962bd45ff5d7a3d04",
          "md5": "24f936e38ea2879e88bce6adfd6db7a2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-1.0.aar",
          "url": "connectivity_plus_debug-1.0.aar",
          "size": 9326,
          "sha512": "0603196a7cd0185da377b3611853b67fa0132cbb59f5d3944e78a347dba252c09ac7673305498fe66755769afeec1d8e1159d0ea8cfeedff9bf262944bf268b5",
          "sha256": "89ebf5dbd137924a2d9938a9125cd055fad8ad23e3d2df857f1122e2cd2e6efa",
          "sha1": "a52b41b9c9e1c24742d30a9962bd45ff5d7a3d04",
          "md5": "24f936e38ea2879e88bce6adfd6db7a2"
        }
      ]
    }
  ]
}
