{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 106183,
          "sha512": "4c04d48bbecbb7e7495665dc002aa371f396493871164d8cd28671699512bde0c8d23e1d0cd895189828d4b20c66bbb7b508c394c973d403c6c8baae49da3482",
          "sha256": "70b95fb4ec1ceff29b111bd70e47f86723e792fdfdda78e04689e4f032a3b758",
          "sha1": "89aed0a12e37cf7fc412273e8f29e59b7cfe0c79",
          "md5": "8b2320581edfc0bc5c9b5ad1bfa5f1b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 106183,
          "sha512": "4c04d48bbecbb7e7495665dc002aa371f396493871164d8cd28671699512bde0c8d23e1d0cd895189828d4b20c66bbb7b508c394c973d403c6c8baae49da3482",
          "sha256": "70b95fb4ec1ceff29b111bd70e47f86723e792fdfdda78e04689e4f032a3b758",
          "sha1": "89aed0a12e37cf7fc412273e8f29e59b7cfe0c79",
          "md5": "8b2320581edfc0bc5c9b5ad1bfa5f1b0"
        }
      ]
    }
  ]
}
