{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "size": 9971,
          "sha512": "7732bf8a3e3af9f1692263d539999abc2ef522534063063a011b214efdb39f8cf2fe33fd1e050d3decd5b0d8ef4ae6a784d9974ed2e888128e3c52c833a9bb42",
          "sha256": "ac5d978c3be096c8dcebe32d82b000750b986390d3daf045b2749848357d4070",
          "sha1": "24ea164b0e418e94a240874412400b87964527d5",
          "md5": "c84a7f0dedb33e9ee75e7bf13c73747a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "size": 9971,
          "sha512": "7732bf8a3e3af9f1692263d539999abc2ef522534063063a011b214efdb39f8cf2fe33fd1e050d3decd5b0d8ef4ae6a784d9974ed2e888128e3c52c833a9bb42",
          "sha256": "ac5d978c3be096c8dcebe32d82b000750b986390d3daf045b2749848357d4070",
          "sha1": "24ea164b0e418e94a240874412400b87964527d5",
          "md5": "c84a7f0dedb33e9ee75e7bf13c73747a"
        }
      ]
    }
  ]
}
