{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9335,
          "sha512": "575f004516d2698b2f4f3df3ed859bcfbd6976034e209fb7479d65e7a92b5f7617d53142fc1d0464ea4cb3997aef4adfa61dcf9036b954ad8b61c8c1eeb0ed7a",
          "sha256": "349e018cb1ffaae490b2fedcbfd1f82f871b610f9c4edd5548b8a7c6343be542",
          "sha1": "dca8ae1824c005df9c325842bb0f819c5dc3e22b",
          "md5": "423daa910c3b9fda94eb2b5635b41e29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9335,
          "sha512": "575f004516d2698b2f4f3df3ed859bcfbd6976034e209fb7479d65e7a92b5f7617d53142fc1d0464ea4cb3997aef4adfa61dcf9036b954ad8b61c8c1eeb0ed7a",
          "sha256": "349e018cb1ffaae490b2fedcbfd1f82f871b610f9c4edd5548b8a7c6343be542",
          "sha1": "dca8ae1824c005df9c325842bb0f819c5dc3e22b",
          "md5": "423daa910c3b9fda94eb2b5635b41e29"
        }
      ]
    }
  ]
}
