{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 14442,
          "sha512": "38ac150aab790b2fa4b0a751eb2e905b11fa180af9491c13453a53c1569507b94e4575be9d9c7d70b66141205f141056e34315322be14e8d594e7d0d738bbbc4",
          "sha256": "17f10e82616ba053fe1e0b8794f5d42ab41d4e67b80d1259dcdb4eb8baf27244",
          "sha1": "92573f8f26e6a9149dab6f0f40a611bec29a45c0",
          "md5": "44e4223ff1e8a27039148cafdf653f08"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 14442,
          "sha512": "38ac150aab790b2fa4b0a751eb2e905b11fa180af9491c13453a53c1569507b94e4575be9d9c7d70b66141205f141056e34315322be14e8d594e7d0d738bbbc4",
          "sha256": "17f10e82616ba053fe1e0b8794f5d42ab41d4e67b80d1259dcdb4eb8baf27244",
          "sha1": "92573f8f26e6a9149dab6f0f40a611bec29a45c0",
          "md5": "44e4223ff1e8a27039148cafdf653f08"
        }
      ]
    }
  ]
}
