{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex-1.0-debug.aar",
          "url": "open_filex-1.0-debug.aar",
          "size": 14442,
          "sha512": "38ac150aab790b2fa4b0a751eb2e905b11fa180af9491c13453a53c1569507b94e4575be9d9c7d70b66141205f141056e34315322be14e8d594e7d0d738bbbc4",
          "sha256": "17f10e82616ba053fe1e0b8794f5d42ab41d4e67b80d1259dcdb4eb8baf27244",
          "sha1": "92573f8f26e6a9149dab6f0f40a611bec29a45c0",
          "md5": "44e4223ff1e8a27039148cafdf653f08"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex-1.0-debug.aar",
          "url": "open_filex-1.0-debug.aar",
          "size": 14442,
          "sha512": "38ac150aab790b2fa4b0a751eb2e905b11fa180af9491c13453a53c1569507b94e4575be9d9c7d70b66141205f141056e34315322be14e8d594e7d0d738bbbc4",
          "sha256": "17f10e82616ba053fe1e0b8794f5d42ab41d4e67b80d1259dcdb4eb8baf27244",
          "sha1": "92573f8f26e6a9149dab6f0f40a611bec29a45c0",
          "md5": "44e4223ff1e8a27039148cafdf653f08"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex-1.0-release.aar",
          "url": "open_filex-1.0-release.aar",
          "size": 13860,
          "sha512": "b37253514bb47767544d5f8a82bdf51810a2d3f73f213fd81991d2f7823a411be4e91d243c1f5fa8308e3049faaacf02cd47804b0fcb8ec61d6bd55d1b3c6fb8",
          "sha256": "0bf38d8218c35efcaebb0b82bb31564e93565f2769fadca67ef587191a34a290",
          "sha1": "8c96d5cc2e219ef3910e4cc71fa82ce9b431735d",
          "md5": "6feb9ca103a10fa7e0544739c9dda3d5"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex-1.0-release.aar",
          "url": "open_filex-1.0-release.aar",
          "size": 13860,
          "sha512": "b37253514bb47767544d5f8a82bdf51810a2d3f73f213fd81991d2f7823a411be4e91d243c1f5fa8308e3049faaacf02cd47804b0fcb8ec61d6bd55d1b3c6fb8",
          "sha256": "0bf38d8218c35efcaebb0b82bb31564e93565f2769fadca67ef587191a34a290",
          "sha1": "8c96d5cc2e219ef3910e4cc71fa82ce9b431735d",
          "md5": "6feb9ca103a10fa7e0544739c9dda3d5"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex-1.0-profile.aar",
          "url": "open_filex-1.0-profile.aar",
          "size": 13858,
          "sha512": "e51c5a3b3c294a5e8baac4ec928f476645cf5863515e8574168c1ee11a9991588b0020e8f995f648d497829603efc78d67743cc53a39a3ad9e7d9eb51ad56626",
          "sha256": "112cf53d57e98672946de148876bfb5e8b89a55458ea9601154ffcfce02d2664",
          "sha1": "a98a68a621629532df3f6b39ad6a29cb9cb30cfc",
          "md5": "1b02b000f6d96625087ddee720d24b65"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex-1.0-profile.aar",
          "url": "open_filex-1.0-profile.aar",
          "size": 13858,
          "sha512": "e51c5a3b3c294a5e8baac4ec928f476645cf5863515e8574168c1ee11a9991588b0020e8f995f648d497829603efc78d67743cc53a39a3ad9e7d9eb51ad56626",
          "sha256": "112cf53d57e98672946de148876bfb5e8b89a55458ea9601154ffcfce02d2664",
          "sha1": "a98a68a621629532df3f6b39ad6a29cb9cb30cfc",
          "md5": "1b02b000f6d96625087ddee720d24b65"
        }
      ]
    }
  ]
}
