{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 15031,
          "sha512": "8cca3d535a1437c43ec8a4651c5ef8e2c49175bc22cfded05fba00e77d828b556f756ea1ebef8153c6f3aa34fe734c57d0f4bf7d0adc508a988bcf615b62f83a",
          "sha256": "e1c6837aa071b50303a8e586bdab749b3d9a3a99b3ad99b974cc7e9727338bc6",
          "sha1": "cd519da646c6fbd096f09c4b2029089c7fe8c584",
          "md5": "1969ed071e504a45d0bc862b11d9664d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 15031,
          "sha512": "8cca3d535a1437c43ec8a4651c5ef8e2c49175bc22cfded05fba00e77d828b556f756ea1ebef8153c6f3aa34fe734c57d0f4bf7d0adc508a988bcf615b62f83a",
          "sha256": "e1c6837aa071b50303a8e586bdab749b3d9a3a99b3ad99b974cc7e9727338bc6",
          "sha1": "cd519da646c6fbd096f09c4b2029089c7fe8c584",
          "md5": "1969ed071e504a45d0bc862b11d9664d"
        }
      ]
    }
  ]
}
