{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-debug.aar",
          "url": "connectivity_plus-1.0-debug.aar",
          "size": 9326,
          "sha512": "0603196a7cd0185da377b3611853b67fa0132cbb59f5d3944e78a347dba252c09ac7673305498fe66755769afeec1d8e1159d0ea8cfeedff9bf262944bf268b5",
          "sha256": "89ebf5dbd137924a2d9938a9125cd055fad8ad23e3d2df857f1122e2cd2e6efa",
          "sha1": "a52b41b9c9e1c24742d30a9962bd45ff5d7a3d04",
          "md5": "24f936e38ea2879e88bce6adfd6db7a2"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-debug.aar",
          "url": "connectivity_plus-1.0-debug.aar",
          "size": 9326,
          "sha512": "0603196a7cd0185da377b3611853b67fa0132cbb59f5d3944e78a347dba252c09ac7673305498fe66755769afeec1d8e1159d0ea8cfeedff9bf262944bf268b5",
          "sha256": "89ebf5dbd137924a2d9938a9125cd055fad8ad23e3d2df857f1122e2cd2e6efa",
          "sha1": "a52b41b9c9e1c24742d30a9962bd45ff5d7a3d04",
          "md5": "24f936e38ea2879e88bce6adfd6db7a2"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-release.aar",
          "url": "connectivity_plus-1.0-release.aar",
          "size": 8958,
          "sha512": "cada5dac1ebbbc32e753df6ea8a72d017b439ad164ba96c14d6d0ec92f663445e8ed161357f40a229e064d866f526232e8b30bfdfa939781475e6e11e44dd773",
          "sha256": "e3cbaf9b55e5a38d324dda531c192b75f3072ce0d2e49765492aa6d383972bb3",
          "sha1": "00edcf359d3955d7fb337364fd375bb26ebdde00",
          "md5": "7c260493021e5f68ccfb3ca2917994c8"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-release.aar",
          "url": "connectivity_plus-1.0-release.aar",
          "size": 8958,
          "sha512": "cada5dac1ebbbc32e753df6ea8a72d017b439ad164ba96c14d6d0ec92f663445e8ed161357f40a229e064d866f526232e8b30bfdfa939781475e6e11e44dd773",
          "sha256": "e3cbaf9b55e5a38d324dda531c192b75f3072ce0d2e49765492aa6d383972bb3",
          "sha1": "00edcf359d3955d7fb337364fd375bb26ebdde00",
          "md5": "7c260493021e5f68ccfb3ca2917994c8"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-profile.aar",
          "url": "connectivity_plus-1.0-profile.aar",
          "size": 8959,
          "sha512": "5ff1f4be6724ef245d1d5803a3a86acc5d4b4c965d64343a64a7a57ac21a6531973e46227105bef50722594d20eea1b70859c9944eceffb81357bd7148491cff",
          "sha256": "ba390112a26727c597ad4c698fc07f2e53d1ad4295b1ee648dc8bf4a0260aa96",
          "sha1": "6045e94da07f425de81ff779fb397534f75423f1",
          "md5": "82c631498273b39c91ea0446d9448d17"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-profile.aar",
          "url": "connectivity_plus-1.0-profile.aar",
          "size": 8959,
          "sha512": "5ff1f4be6724ef245d1d5803a3a86acc5d4b4c965d64343a64a7a57ac21a6531973e46227105bef50722594d20eea1b70859c9944eceffb81357bd7148491cff",
          "sha256": "ba390112a26727c597ad4c698fc07f2e53d1ad4295b1ee648dc8bf4a0260aa96",
          "sha1": "6045e94da07f425de81ff779fb397534f75423f1",
          "md5": "82c631498273b39c91ea0446d9448d17"
        }
      ]
    }
  ]
}
