{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_profile-1.0.aar",
          "url": "flutter_secure_storage_profile-1.0.aar",
          "size": 26166,
          "sha512": "204842243d364f0e131a32ed22c67ea977b58411966724f1458b3126452845c93889dc592453d936d7058ff125688a7b3372a3fa52aa3904fe42d5570b5a8e53",
          "sha256": "a33d6167e94ec4cb8d600dfb651365a8dac8b3a8f82b00e1e59924dac71befc9",
          "sha1": "88bee76647fec791cea9993b834415afa56bf7d3",
          "md5": "6dc93d9a15f1f5e1c092bcaaa90e86a8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_profile-1.0.aar",
          "url": "flutter_secure_storage_profile-1.0.aar",
          "size": 26166,
          "sha512": "204842243d364f0e131a32ed22c67ea977b58411966724f1458b3126452845c93889dc592453d936d7058ff125688a7b3372a3fa52aa3904fe42d5570b5a8e53",
          "sha256": "a33d6167e94ec4cb8d600dfb651365a8dac8b3a8f82b00e1e59924dac71befc9",
          "sha1": "88bee76647fec791cea9993b834415afa56bf7d3",
          "md5": "6dc93d9a15f1f5e1c092bcaaa90e86a8"
        }
      ]
    }
  ]
}
