{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-1.0-debug.aar",
          "url": "flutter_secure_storage-1.0-debug.aar",
          "size": 27430,
          "sha512": "1ff23f0883416197e509961a4cbfe02f21fbeb33536ed49defbd4baefd4a477bd8ca8e71455cf45ab175bfad981a7bca597f9fd50fbaacb9f68ed1126c872c52",
          "sha256": "a6ab71e98f646329aae65b18f54ef1e0208a961a9de90cd2da64af8555ba2f3c",
          "sha1": "3a283263119c37572a27a59806f525c8cff6478d",
          "md5": "fe3057400c0760c731f831473e39eb84"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-1.0-debug.aar",
          "url": "flutter_secure_storage-1.0-debug.aar",
          "size": 27430,
          "sha512": "1ff23f0883416197e509961a4cbfe02f21fbeb33536ed49defbd4baefd4a477bd8ca8e71455cf45ab175bfad981a7bca597f9fd50fbaacb9f68ed1126c872c52",
          "sha256": "a6ab71e98f646329aae65b18f54ef1e0208a961a9de90cd2da64af8555ba2f3c",
          "sha1": "3a283263119c37572a27a59806f525c8cff6478d",
          "md5": "fe3057400c0760c731f831473e39eb84"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-1.0-release.aar",
          "url": "flutter_secure_storage-1.0-release.aar",
          "size": 26164,
          "sha512": "5546c2060948996f271bdd2a1db76757de0cfbd655b89f9ae71ffc1a1c36e298b42a2d57e18fc6efb4878993fdf545ad0a8bd8885290b2dbe30e066c2ea611ab",
          "sha256": "f92e42bf6309b7f757d49ebc891ccd362cb39fdd011c2d9fb73aea296c35885c",
          "sha1": "a348b2db614b2edb7822dbe5a706730d417d7000",
          "md5": "a3c711061a351b8b1d25c6baffcd1a14"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-1.0-release.aar",
          "url": "flutter_secure_storage-1.0-release.aar",
          "size": 26164,
          "sha512": "5546c2060948996f271bdd2a1db76757de0cfbd655b89f9ae71ffc1a1c36e298b42a2d57e18fc6efb4878993fdf545ad0a8bd8885290b2dbe30e066c2ea611ab",
          "sha256": "f92e42bf6309b7f757d49ebc891ccd362cb39fdd011c2d9fb73aea296c35885c",
          "sha1": "a348b2db614b2edb7822dbe5a706730d417d7000",
          "md5": "a3c711061a351b8b1d25c6baffcd1a14"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-1.0-profile.aar",
          "url": "flutter_secure_storage-1.0-profile.aar",
          "size": 26166,
          "sha512": "204842243d364f0e131a32ed22c67ea977b58411966724f1458b3126452845c93889dc592453d936d7058ff125688a7b3372a3fa52aa3904fe42d5570b5a8e53",
          "sha256": "a33d6167e94ec4cb8d600dfb651365a8dac8b3a8f82b00e1e59924dac71befc9",
          "sha1": "88bee76647fec791cea9993b834415afa56bf7d3",
          "md5": "6dc93d9a15f1f5e1c092bcaaa90e86a8"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-1.0-profile.aar",
          "url": "flutter_secure_storage-1.0-profile.aar",
          "size": 26166,
          "sha512": "204842243d364f0e131a32ed22c67ea977b58411966724f1458b3126452845c93889dc592453d936d7058ff125688a7b3372a3fa52aa3904fe42d5570b5a8e53",
          "sha256": "a33d6167e94ec4cb8d600dfb651365a8dac8b3a8f82b00e1e59924dac71befc9",
          "sha1": "88bee76647fec791cea9993b834415afa56bf7d3",
          "md5": "6dc93d9a15f1f5e1c092bcaaa90e86a8"
        }
      ]
    }
  ]
}
