{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.0-debug.aar",
          "url": "path_provider_android-1.0-debug.aar",
          "size": 12988,
          "sha512": "ae9050268dc836825d49d332357ee09b065d9b7ecbd62788178ffd10adc79898445151ea6f0f03b85a67f7ce8a37db87a67f3dde8205434995a1fb980ed685e6",
          "sha256": "7d71748741d5d4af7d3eb8610c05bea66504345d1452dd239b1617e01442ae36",
          "sha1": "fd998d8e85aa883cf7e8b3e8cdc34f1813b197cc",
          "md5": "2dec53e9d8f8c7671acb37bd8ab937ec"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.0-debug.aar",
          "url": "path_provider_android-1.0-debug.aar",
          "size": 12988,
          "sha512": "ae9050268dc836825d49d332357ee09b065d9b7ecbd62788178ffd10adc79898445151ea6f0f03b85a67f7ce8a37db87a67f3dde8205434995a1fb980ed685e6",
          "sha256": "7d71748741d5d4af7d3eb8610c05bea66504345d1452dd239b1617e01442ae36",
          "sha1": "fd998d8e85aa883cf7e8b3e8cdc34f1813b197cc",
          "md5": "2dec53e9d8f8c7671acb37bd8ab937ec"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.0-release.aar",
          "url": "path_provider_android-1.0-release.aar",
          "size": 12418,
          "sha512": "d2fe8c7c4964ecc8d0fc74754b52c098de57e1a008b2210f27227c589bc9632d39c2d4921802d00f16e6f3088f91aa7153494cd4d60e9ec5bb084b2a4cd7249b",
          "sha256": "e06dfe7c4e634abb8198e6f18961c58cdd989fa4b29b49561bfac7b7cc9567b7",
          "sha1": "028c374aef38d5364eef0bb56631c2664e158885",
          "md5": "d8ae0e55b4ed99127a0545c1e628d5d5"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.0-release.aar",
          "url": "path_provider_android-1.0-release.aar",
          "size": 12418,
          "sha512": "d2fe8c7c4964ecc8d0fc74754b52c098de57e1a008b2210f27227c589bc9632d39c2d4921802d00f16e6f3088f91aa7153494cd4d60e9ec5bb084b2a4cd7249b",
          "sha256": "e06dfe7c4e634abb8198e6f18961c58cdd989fa4b29b49561bfac7b7cc9567b7",
          "sha1": "028c374aef38d5364eef0bb56631c2664e158885",
          "md5": "d8ae0e55b4ed99127a0545c1e628d5d5"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.0-profile.aar",
          "url": "path_provider_android-1.0-profile.aar",
          "size": 12415,
          "sha512": "a29f3cf1741fd0edd85fed9a93957ab9ecc31f356c36ab4085582df8aee147cbf3a6f6933cf949557b5beb73e71f4b1b32ed33863e9bc8287df66c35c4d810c5",
          "sha256": "47f0fe5d1a611ffcd75fd504a3e242c6e4d4e4701c1ebad24226df57b07fbdf4",
          "sha1": "2b12fb65ce3dcf2e8654ec054e574f6e68f11509",
          "md5": "c34316c857c0c32a2ae62810ed7289a4"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.0-profile.aar",
          "url": "path_provider_android-1.0-profile.aar",
          "size": 12415,
          "sha512": "a29f3cf1741fd0edd85fed9a93957ab9ecc31f356c36ab4085582df8aee147cbf3a6f6933cf949557b5beb73e71f4b1b32ed33863e9bc8287df66c35c4d810c5",
          "sha256": "47f0fe5d1a611ffcd75fd504a3e242c6e4d4e4701c1ebad24226df57b07fbdf4",
          "sha1": "2b12fb65ce3dcf2e8654ec054e574f6e68f11509",
          "md5": "c34316c857c0c32a2ae62810ed7289a4"
        }
      ]
    }
  ]
}
