{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.0.aar",
          "url": "local_auth_android_release-1.0.aar",
          "size": 50202,
          "sha512": "6251914a74f75abaa0e897c9ef4b165d50db0d421aafd5655de06af0652d9d5476d6ea86ff7b8e63a55af3e96de87605904a46532ad4bf295b3b823641e4632e",
          "sha256": "c9264422e077a855cd5a3f9c718becfc408ff91a107ae7fb4df35c8399a217f1",
          "sha1": "7966715c9a102496a92f55c68d7a661de08b80e0",
          "md5": "b667703165582642bb760c3281c72672"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.0.aar",
          "url": "local_auth_android_release-1.0.aar",
          "size": 50202,
          "sha512": "6251914a74f75abaa0e897c9ef4b165d50db0d421aafd5655de06af0652d9d5476d6ea86ff7b8e63a55af3e96de87605904a46532ad4bf295b3b823641e4632e",
          "sha256": "c9264422e077a855cd5a3f9c718becfc408ff91a107ae7fb4df35c8399a217f1",
          "sha1": "7966715c9a102496a92f55c68d7a661de08b80e0",
          "md5": "b667703165582642bb760c3281c72672"
        }
      ]
    }
  ]
}
