{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "size": 9970,
          "sha512": "772d9281881f12afdad5bd4d0322755469e5e7a0b5a803a6d9606f86c114835d0f686bc6cfac769327ae827d7f964349ceb2d834dab404b4791a6c12cb89baa8",
          "sha256": "2663581fc0713a8c7295da267d35837eb4e124c80543caf3812a2ca082db0652",
          "sha1": "642857be891256ab9cfcdd0c7fb73a036cded5f2",
          "md5": "858cd1dd4cc0ab3489bf882a8d54245f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_profile-1.0.aar",
          "size": 9970,
          "sha512": "772d9281881f12afdad5bd4d0322755469e5e7a0b5a803a6d9606f86c114835d0f686bc6cfac769327ae827d7f964349ceb2d834dab404b4791a6c12cb89baa8",
          "sha256": "2663581fc0713a8c7295da267d35837eb4e124c80543caf3812a2ca082db0652",
          "sha1": "642857be891256ab9cfcdd0c7fb73a036cded5f2",
          "md5": "858cd1dd4cc0ab3489bf882a8d54245f"
        }
      ]
    }
  ]
}
