{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 106180,
          "sha512": "1394b998b8595d7189dc074fa57b5199937590370165b9e1c099d0ea494a4952bb447b581980ddebb3b669d057f5c2534abe20251319eff0b36afb9e592cac88",
          "sha256": "2c00ceba81f861135f728356e5667b76dc6ea4cee9e6f1c62e523b79c57e0f21",
          "sha1": "d8129711d598004fee160eca08a7a3d8b1f3c47c",
          "md5": "4eda622c59d6d05077067ee970cf2ca5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 106180,
          "sha512": "1394b998b8595d7189dc074fa57b5199937590370165b9e1c099d0ea494a4952bb447b581980ddebb3b669d057f5c2534abe20251319eff0b36afb9e592cac88",
          "sha256": "2c00ceba81f861135f728356e5667b76dc6ea4cee9e6f1c62e523b79c57e0f21",
          "sha1": "d8129711d598004fee160eca08a7a3d8b1f3c47c",
          "md5": "4eda622c59d6d05077067ee970cf2ca5"
        }
      ]
    }
  ]
}
