{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 106089,
          "sha512": "ef85f8073530a5d49777816394e6f53c8c8a7c168f6502803d6cbf341c1ab661c635a128e3386dbb7100a824b120d46f68d4d1e5ea06c21e2daea9aea8a3a491",
          "sha256": "6d754952b0bfccd16a5845ca56594efeb7aac1d469f1fce20ab74c47f7de7991",
          "sha1": "a59833c6fd4bf7f4cc66566fcd5f3f963af2f91e",
          "md5": "3d5987e26e1a0331eb4bf912db4ebe18"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 106089,
          "sha512": "ef85f8073530a5d49777816394e6f53c8c8a7c168f6502803d6cbf341c1ab661c635a128e3386dbb7100a824b120d46f68d4d1e5ea06c21e2daea9aea8a3a491",
          "sha256": "6d754952b0bfccd16a5845ca56594efeb7aac1d469f1fce20ab74c47f7de7991",
          "sha1": "a59833c6fd4bf7f4cc66566fcd5f3f963af2f91e",
          "md5": "3d5987e26e1a0331eb4bf912db4ebe18"
        }
      ]
    }
  ]
}
