{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13858,
          "sha512": "e51c5a3b3c294a5e8baac4ec928f476645cf5863515e8574168c1ee11a9991588b0020e8f995f648d497829603efc78d67743cc53a39a3ad9e7d9eb51ad56626",
          "sha256": "112cf53d57e98672946de148876bfb5e8b89a55458ea9601154ffcfce02d2664",
          "sha1": "a98a68a621629532df3f6b39ad6a29cb9cb30cfc",
          "md5": "1b02b000f6d96625087ddee720d24b65"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13858,
          "sha512": "e51c5a3b3c294a5e8baac4ec928f476645cf5863515e8574168c1ee11a9991588b0020e8f995f648d497829603efc78d67743cc53a39a3ad9e7d9eb51ad56626",
          "sha256": "112cf53d57e98672946de148876bfb5e8b89a55458ea9601154ffcfce02d2664",
          "sha1": "a98a68a621629532df3f6b39ad6a29cb9cb30cfc",
          "md5": "1b02b000f6d96625087ddee720d24b65"
        }
      ]
    }
  ]
}
