{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_safe_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_debug-1.0.aar",
          "url": "open_file_safe_debug-1.0.aar",
          "size": 14321,
          "sha512": "10ae766c67c517bb93e7c13a3c572a2ce241eb289e741ba87bfa6f8b382d288b9df83969c67703fa62686fcaed48499a4c54c36365c4972dcbe61f0a67206280",
          "sha256": "0b187708114a7ffeaca310d270a5fba38a02128a0542df825cb653f11669c8fa",
          "sha1": "6c77f273db34c3b9eead8c32bcbb82ba62c1c4f2",
          "md5": "aee73536955e1d2958b0512c808bc032"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_debug-1.0.aar",
          "url": "open_file_safe_debug-1.0.aar",
          "size": 14321,
          "sha512": "10ae766c67c517bb93e7c13a3c572a2ce241eb289e741ba87bfa6f8b382d288b9df83969c67703fa62686fcaed48499a4c54c36365c4972dcbe61f0a67206280",
          "sha256": "0b187708114a7ffeaca310d270a5fba38a02128a0542df825cb653f11669c8fa",
          "sha1": "6c77f273db34c3b9eead8c32bcbb82ba62c1c4f2",
          "md5": "aee73536955e1d2958b0512c808bc032"
        }
      ]
    }
  ]
}
