{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-debug.aar",
          "url": "local_auth_android-1.0-debug.aar",
          "size": 50986,
          "sha512": "d1c031b676856d866e83a94767768240730751cb74a679e73a96f6e669b821577075597ade206344cd87830e2c0a84c7124858cdb4dfd10551010e8f592845d0",
          "sha256": "f9af80e598968de8180b9e61a34acf09f2ce60d4529930e0cc0ac39b19bfdc6c",
          "sha1": "16b8d509f4e67fc4abfa8de2c4a37fe912ff0ad2",
          "md5": "642f7cf08379c8c76dfe07a516ed151e"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-debug.aar",
          "url": "local_auth_android-1.0-debug.aar",
          "size": 50986,
          "sha512": "d1c031b676856d866e83a94767768240730751cb74a679e73a96f6e669b821577075597ade206344cd87830e2c0a84c7124858cdb4dfd10551010e8f592845d0",
          "sha256": "f9af80e598968de8180b9e61a34acf09f2ce60d4529930e0cc0ac39b19bfdc6c",
          "sha1": "16b8d509f4e67fc4abfa8de2c4a37fe912ff0ad2",
          "md5": "642f7cf08379c8c76dfe07a516ed151e"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-release.aar",
          "url": "local_auth_android-1.0-release.aar",
          "size": 50112,
          "sha512": "1eac0102b58e58720b8a12a61eddf1378a81ba8cb9ecc4f0122f89b53ce6eeefc15e63785de78e49aee7e62e7c65138c51f4610590ccc377f40b0cbbdab1cf2e",
          "sha256": "adca7a16e50185ce67cdab9bc93f9cd26e74e0f22d57425f39d7447fc5152895",
          "sha1": "aa2c93bcff2a47b43f18144e565e73371f3a3439",
          "md5": "f15420c250c4ebd28720e9445e5f8553"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-release.aar",
          "url": "local_auth_android-1.0-release.aar",
          "size": 50112,
          "sha512": "1eac0102b58e58720b8a12a61eddf1378a81ba8cb9ecc4f0122f89b53ce6eeefc15e63785de78e49aee7e62e7c65138c51f4610590ccc377f40b0cbbdab1cf2e",
          "sha256": "adca7a16e50185ce67cdab9bc93f9cd26e74e0f22d57425f39d7447fc5152895",
          "sha1": "aa2c93bcff2a47b43f18144e565e73371f3a3439",
          "md5": "f15420c250c4ebd28720e9445e5f8553"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-profile.aar",
          "url": "local_auth_android-1.0-profile.aar",
          "size": 50115,
          "sha512": "dc4f375e901db0861b643be4bb52af321456f60e3ecd874d6046d9f099861335e4bbfd1673220cf1977cbc0ceac07522f456e787449743080377f0256b108fe7",
          "sha256": "9e4c449e24734f615a6d6851d8dfbb53db17b80e99be6dfaab86417f0ac4b96f",
          "sha1": "314df1936fe7c248c8f68268b42fd6a0263db95c",
          "md5": "0e326c629d819ab907d67023ffa09635"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-profile.aar",
          "url": "local_auth_android-1.0-profile.aar",
          "size": 50115,
          "sha512": "dc4f375e901db0861b643be4bb52af321456f60e3ecd874d6046d9f099861335e4bbfd1673220cf1977cbc0ceac07522f456e787449743080377f0256b108fe7",
          "sha256": "9e4c449e24734f615a6d6851d8dfbb53db17b80e99be6dfaab86417f0ac4b96f",
          "sha1": "314df1936fe7c248c8f68268b42fd6a0263db95c",
          "md5": "0e326c629d819ab907d67023ffa09635"
        }
      ]
    }
  ]
}
