{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-debug.aar",
          "url": "local_auth_android-1.0-debug.aar",
          "size": 51087,
          "sha512": "adf586cb2dfa03eee032518f08321a4f06ebb8774034a78dddea89e784b5c3070c2fb99a5b801591b7da1c3a8a279d311c97e0130daead15eaf94eb77462742f",
          "sha256": "9adb95e4d0737ab2cdcfcda06b6a12ee0eb110afe581cdd37aa4fe4658f533bc",
          "sha1": "51a856c966b9c56adfc7664882ae5a1fe17b9af7",
          "md5": "52a42a1989fa7ccf4d9b158598a3f8e9"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-debug.aar",
          "url": "local_auth_android-1.0-debug.aar",
          "size": 51087,
          "sha512": "adf586cb2dfa03eee032518f08321a4f06ebb8774034a78dddea89e784b5c3070c2fb99a5b801591b7da1c3a8a279d311c97e0130daead15eaf94eb77462742f",
          "sha256": "9adb95e4d0737ab2cdcfcda06b6a12ee0eb110afe581cdd37aa4fe4658f533bc",
          "sha1": "51a856c966b9c56adfc7664882ae5a1fe17b9af7",
          "md5": "52a42a1989fa7ccf4d9b158598a3f8e9"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-release.aar",
          "url": "local_auth_android-1.0-release.aar",
          "size": 50202,
          "sha512": "6251914a74f75abaa0e897c9ef4b165d50db0d421aafd5655de06af0652d9d5476d6ea86ff7b8e63a55af3e96de87605904a46532ad4bf295b3b823641e4632e",
          "sha256": "c9264422e077a855cd5a3f9c718becfc408ff91a107ae7fb4df35c8399a217f1",
          "sha1": "7966715c9a102496a92f55c68d7a661de08b80e0",
          "md5": "b667703165582642bb760c3281c72672"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-release.aar",
          "url": "local_auth_android-1.0-release.aar",
          "size": 50202,
          "sha512": "6251914a74f75abaa0e897c9ef4b165d50db0d421aafd5655de06af0652d9d5476d6ea86ff7b8e63a55af3e96de87605904a46532ad4bf295b3b823641e4632e",
          "sha256": "c9264422e077a855cd5a3f9c718becfc408ff91a107ae7fb4df35c8399a217f1",
          "sha1": "7966715c9a102496a92f55c68d7a661de08b80e0",
          "md5": "b667703165582642bb760c3281c72672"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-profile.aar",
          "url": "local_auth_android-1.0-profile.aar",
          "size": 50204,
          "sha512": "907a892270d34d183810883cd0868534af2e13d1f2a94c094eb72e8a9413998f214dca51ca77d0d952dc774a8bb6bed42dfd0bfcb4b7c5a391c8b69729367f1c",
          "sha256": "598842c89d02253e90714f309f0913fafdcfbebf3a6f2f7fd18b921cb10ea9f6",
          "sha1": "c0071ad801613e8d0925606e24c149cfe30fd17c",
          "md5": "931d407d95d51674ac0ca99618783342"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-profile.aar",
          "url": "local_auth_android-1.0-profile.aar",
          "size": 50204,
          "sha512": "907a892270d34d183810883cd0868534af2e13d1f2a94c094eb72e8a9413998f214dca51ca77d0d952dc774a8bb6bed42dfd0bfcb4b7c5a391c8b69729367f1c",
          "sha256": "598842c89d02253e90714f309f0913fafdcfbebf3a6f2f7fd18b921cb10ea9f6",
          "sha1": "c0071ad801613e8d0925606e24c149cfe30fd17c",
          "md5": "931d407d95d51674ac0ca99618783342"
        }
      ]
    }
  ]
}
