{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13860,
          "sha512": "b37253514bb47767544d5f8a82bdf51810a2d3f73f213fd81991d2f7823a411be4e91d243c1f5fa8308e3049faaacf02cd47804b0fcb8ec61d6bd55d1b3c6fb8",
          "sha256": "0bf38d8218c35efcaebb0b82bb31564e93565f2769fadca67ef587191a34a290",
          "sha1": "8c96d5cc2e219ef3910e4cc71fa82ce9b431735d",
          "md5": "6feb9ca103a10fa7e0544739c9dda3d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13860,
          "sha512": "b37253514bb47767544d5f8a82bdf51810a2d3f73f213fd81991d2f7823a411be4e91d243c1f5fa8308e3049faaacf02cd47804b0fcb8ec61d6bd55d1b3c6fb8",
          "sha256": "0bf38d8218c35efcaebb0b82bb31564e93565f2769fadca67ef587191a34a290",
          "sha1": "8c96d5cc2e219ef3910e4cc71fa82ce9b431735d",
          "md5": "6feb9ca103a10fa7e0544739c9dda3d5"
        }
      ]
    }
  ]
}
