{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 12986,
          "sha512": "84a8d87290053a4de55cf2df83763e81dcd6d7b3d5c1f96211278ad569da9c4a276a1fb300b3cde9c0841c373a78574269a852a679bac6c206b2fa40b9827641",
          "sha256": "fd9aecf7f92ac97de38acf1162a66a76480b848a3f7f4133ff2d0adb16407fea",
          "sha1": "23fcc9c40c4613ad95a81ad2e7b3e3919386ce06",
          "md5": "d4e8ebc757cb4d8993c26d620593826d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 12986,
          "sha512": "84a8d87290053a4de55cf2df83763e81dcd6d7b3d5c1f96211278ad569da9c4a276a1fb300b3cde9c0841c373a78574269a852a679bac6c206b2fa40b9827641",
          "sha256": "fd9aecf7f92ac97de38acf1162a66a76480b848a3f7f4133ff2d0adb16407fea",
          "sha1": "23fcc9c40c4613ad95a81ad2e7b3e3919386ce06",
          "md5": "d4e8ebc757cb4d8993c26d620593826d"
        }
      ]
    }
  ]
}
