{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 12988,
          "sha512": "ae9050268dc836825d49d332357ee09b065d9b7ecbd62788178ffd10adc79898445151ea6f0f03b85a67f7ce8a37db87a67f3dde8205434995a1fb980ed685e6",
          "sha256": "7d71748741d5d4af7d3eb8610c05bea66504345d1452dd239b1617e01442ae36",
          "sha1": "fd998d8e85aa883cf7e8b3e8cdc34f1813b197cc",
          "md5": "2dec53e9d8f8c7671acb37bd8ab937ec"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 12988,
          "sha512": "ae9050268dc836825d49d332357ee09b065d9b7ecbd62788178ffd10adc79898445151ea6f0f03b85a67f7ce8a37db87a67f3dde8205434995a1fb980ed685e6",
          "sha256": "7d71748741d5d4af7d3eb8610c05bea66504345d1452dd239b1617e01442ae36",
          "sha1": "fd998d8e85aa883cf7e8b3e8cdc34f1813b197cc",
          "md5": "2dec53e9d8f8c7671acb37bd8ab937ec"
        }
      ]
    }
  ]
}
