{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle-1.0-debug.aar",
          "url": "flutter_plugin_android_lifecycle-1.0-debug.aar",
          "size": 4813,
          "sha512": "479ce0a26a74f691ffcb86790f2d1a113232d8c4982bf74c8c928758b1ae13bbb6dfa24540c3e8e077cb2bc01a8b92623da45797733be43d9d2d71a2999e6825",
          "sha256": "baec892697184900756b701b92379a2a0f1fb122669fa7d5d286615dc3d7c18d",
          "sha1": "9f0445b6d6e54598edb4a161e99b2886baaf9d8c",
          "md5": "7b8827a51291e20488c12e46424558e8"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle-1.0-debug.aar",
          "url": "flutter_plugin_android_lifecycle-1.0-debug.aar",
          "size": 4813,
          "sha512": "479ce0a26a74f691ffcb86790f2d1a113232d8c4982bf74c8c928758b1ae13bbb6dfa24540c3e8e077cb2bc01a8b92623da45797733be43d9d2d71a2999e6825",
          "sha256": "baec892697184900756b701b92379a2a0f1fb122669fa7d5d286615dc3d7c18d",
          "sha1": "9f0445b6d6e54598edb4a161e99b2886baaf9d8c",
          "md5": "7b8827a51291e20488c12e46424558e8"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle-1.0-release.aar",
          "url": "flutter_plugin_android_lifecycle-1.0-release.aar",
          "size": 4680,
          "sha512": "d030d8e056b5769b5f3f6a36ed5653846f3a0d7a5081c4b681fa160f76056956168c473e8d7b87f610578c9486440d5298ee84e3150772a8902fdb863e3fc82a",
          "sha256": "c3e663430982f43def018a84f6d10fbc438a5defec13c8ead43ffbe3aa800e32",
          "sha1": "d97a8da400ac5ec5ef30aac9b615cf09f2940b94",
          "md5": "67882703db2b8bd093a355d3c0c4fa1c"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle-1.0-release.aar",
          "url": "flutter_plugin_android_lifecycle-1.0-release.aar",
          "size": 4680,
          "sha512": "d030d8e056b5769b5f3f6a36ed5653846f3a0d7a5081c4b681fa160f76056956168c473e8d7b87f610578c9486440d5298ee84e3150772a8902fdb863e3fc82a",
          "sha256": "c3e663430982f43def018a84f6d10fbc438a5defec13c8ead43ffbe3aa800e32",
          "sha1": "d97a8da400ac5ec5ef30aac9b615cf09f2940b94",
          "md5": "67882703db2b8bd093a355d3c0c4fa1c"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle-1.0-profile.aar",
          "url": "flutter_plugin_android_lifecycle-1.0-profile.aar",
          "size": 4676,
          "sha512": "be4f3722eeb92a5213423fa37e1aaaefccbc5bac898f97db4bcc42c174bc70ac7cc0f63ab8592a3fb5259598a92ff9411606009f60ffe9fd36eaafc65efe2969",
          "sha256": "8443cacf6cc93b51c9de876a5100c2cce3c160a092a1b5a5c4712d3bdf563ce4",
          "sha1": "e2219feb23f4b0a9e9ecbe6c918078508d035715",
          "md5": "72441e9162a56aa2ec7bfb947150d2e4"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle-1.0-profile.aar",
          "url": "flutter_plugin_android_lifecycle-1.0-profile.aar",
          "size": 4676,
          "sha512": "be4f3722eeb92a5213423fa37e1aaaefccbc5bac898f97db4bcc42c174bc70ac7cc0f63ab8592a3fb5259598a92ff9411606009f60ffe9fd36eaafc65efe2969",
          "sha256": "8443cacf6cc93b51c9de876a5100c2cce3c160a092a1b5a5c4712d3bdf563ce4",
          "sha1": "e2219feb23f4b0a9e9ecbe6c918078508d035715",
          "md5": "72441e9162a56aa2ec7bfb947150d2e4"
        }
      ]
    }
  ]
}
