{
  "formatVersion": "1.1",
  "component": {
    "group": "appmire.be.flutterjailbreakdetection",
    "module": "flutter_jailbreak_detection_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_release-1.0.aar",
          "url": "flutter_jailbreak_detection_release-1.0.aar",
          "size": 7337,
          "sha512": "87ae7e7c85b304e04f144cf2a724583643a171076b0b557df5c51a1da95650e91f480ea037fe3a12f54d8cfbc6707ce09a5e53798628eb08ba3afd04c9779802",
          "sha256": "92b2410caede6751380b9eb400c934773ada00c5e9b895394c50b12c4585791e",
          "sha1": "bdc8edd97cb0657ce312154c62f0bb62858e3121",
          "md5": "f95fff0ede8bd4a9f4b9ccf324bad34e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_release-1.0.aar",
          "url": "flutter_jailbreak_detection_release-1.0.aar",
          "size": 7337,
          "sha512": "87ae7e7c85b304e04f144cf2a724583643a171076b0b557df5c51a1da95650e91f480ea037fe3a12f54d8cfbc6707ce09a5e53798628eb08ba3afd04c9779802",
          "sha256": "92b2410caede6751380b9eb400c934773ada00c5e9b895394c50b12c4585791e",
          "sha1": "bdc8edd97cb0657ce312154c62f0bb62858e3121",
          "md5": "f95fff0ede8bd4a9f4b9ccf324bad34e"
        }
      ]
    }
  ]
}
