{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-1.0.aar",
          "url": "connectivity_plus_release-1.0.aar",
          "size": 8958,
          "sha512": "cada5dac1ebbbc32e753df6ea8a72d017b439ad164ba96c14d6d0ec92f663445e8ed161357f40a229e064d866f526232e8b30bfdfa939781475e6e11e44dd773",
          "sha256": "e3cbaf9b55e5a38d324dda531c192b75f3072ce0d2e49765492aa6d383972bb3",
          "sha1": "00edcf359d3955d7fb337364fd375bb26ebdde00",
          "md5": "7c260493021e5f68ccfb3ca2917994c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-1.0.aar",
          "url": "connectivity_plus_release-1.0.aar",
          "size": 8958,
          "sha512": "cada5dac1ebbbc32e753df6ea8a72d017b439ad164ba96c14d6d0ec92f663445e8ed161357f40a229e064d866f526232e8b30bfdfa939781475e6e11e44dd773",
          "sha256": "e3cbaf9b55e5a38d324dda531c192b75f3072ce0d2e49765492aa6d383972bb3",
          "sha1": "00edcf359d3955d7fb337364fd375bb26ebdde00",
          "md5": "7c260493021e5f68ccfb3ca2917994c8"
        }
      ]
    }
  ]
}
