{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 15027,
          "sha512": "5d7653a73954192edefa1a9bac9954000457bc168274f4358c477769042bd7cfb5c3b3d062819f5a210d3777196f447ef78b19634df48d196561a9c9ddf6290f",
          "sha256": "45e70b13cb55e7cb5be32d7f69b745a0b7e4b1c593d7234c2482a8215e34a4f4",
          "sha1": "50acf5d5a320ffe5e39cc87ae37674a3922883de",
          "md5": "1a6d267c5bce741f7953770642b072ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 15027,
          "sha512": "5d7653a73954192edefa1a9bac9954000457bc168274f4358c477769042bd7cfb5c3b3d062819f5a210d3777196f447ef78b19634df48d196561a9c9ddf6290f",
          "sha256": "45e70b13cb55e7cb5be32d7f69b745a0b7e4b1c593d7234c2482a8215e34a4f4",
          "sha1": "50acf5d5a320ffe5e39cc87ae37674a3922883de",
          "md5": "1a6d267c5bce741f7953770642b072ef"
        }
      ]
    }
  ]
}
