{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12415,
          "sha512": "a29f3cf1741fd0edd85fed9a93957ab9ecc31f356c36ab4085582df8aee147cbf3a6f6933cf949557b5beb73e71f4b1b32ed33863e9bc8287df66c35c4d810c5",
          "sha256": "47f0fe5d1a611ffcd75fd504a3e242c6e4d4e4701c1ebad24226df57b07fbdf4",
          "sha1": "2b12fb65ce3dcf2e8654ec054e574f6e68f11509",
          "md5": "c34316c857c0c32a2ae62810ed7289a4"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12415,
          "sha512": "a29f3cf1741fd0edd85fed9a93957ab9ecc31f356c36ab4085582df8aee147cbf3a6f6933cf949557b5beb73e71f4b1b32ed33863e9bc8287df66c35c4d810c5",
          "sha256": "47f0fe5d1a611ffcd75fd504a3e242c6e4d4e4701c1ebad24226df57b07fbdf4",
          "sha1": "2b12fb65ce3dcf2e8654ec054e574f6e68f11509",
          "md5": "c34316c857c0c32a2ae62810ed7289a4"
        }
      ]
    }
  ]
}
