{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12405,
          "sha512": "a04cdc4b4c007aafb7203c58b37c46b1f8aee7836c0dc1daf873efb68e263020ad5b42cc9d1633da575c78bb6c883070f2d74bbdfcadf619402a07e8f2fcbcab",
          "sha256": "c754bd30a281dd2e7a680e83ec39f137acc7fdac31cb30ffeb88e9a04021bc73",
          "sha1": "60282b8749ed70f611731196562aede36cb097cb",
          "md5": "48ec5291f0de03593b437517e2afad03"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12405,
          "sha512": "a04cdc4b4c007aafb7203c58b37c46b1f8aee7836c0dc1daf873efb68e263020ad5b42cc9d1633da575c78bb6c883070f2d74bbdfcadf619402a07e8f2fcbcab",
          "sha256": "c754bd30a281dd2e7a680e83ec39f137acc7fdac31cb30ffeb88e9a04021bc73",
          "sha1": "60282b8749ed70f611731196562aede36cb097cb",
          "md5": "48ec5291f0de03593b437517e2afad03"
        }
      ]
    }
  ]
}
