{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 112837,
          "sha512": "1091715c7b93dd700966c7dca1ea766ab9f8752c945408ef5630838ce7a3a359e635c0c5d1677770c3440f0a57a9166a18a62d37c963ee76a430f66c38216b59",
          "sha256": "a2b10001f3ce84d6aee9713285c7fda544a8e7a60716cf211b1213772691d8ad",
          "sha1": "9aece607f67172aa54926628668b84016fec2118",
          "md5": "164796e72d92f9b20a34559f5d280e18"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 112837,
          "sha512": "1091715c7b93dd700966c7dca1ea766ab9f8752c945408ef5630838ce7a3a359e635c0c5d1677770c3440f0a57a9166a18a62d37c963ee76a430f66c38216b59",
          "sha256": "a2b10001f3ce84d6aee9713285c7fda544a8e7a60716cf211b1213772691d8ad",
          "sha1": "9aece607f67172aa54926628668b84016fec2118",
          "md5": "164796e72d92f9b20a34559f5d280e18"
        }
      ]
    }
  ]
}
