{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android-1.0-debug.aar",
          "url": "url_launcher_android-1.0-debug.aar",
          "size": 15662,
          "sha512": "9fe1c1f40d3c85d12c4ef716132484dd872d653e0ff0a90f2d9fda05492c22d87012d65a3ff666f1bb2f16aff9ef2db88433aa7322a4e6cd661a0b175aca2902",
          "sha256": "9e7cde98eb61d00b350fecf89123610dbd246c23318a695f0eba6422e095b243",
          "sha1": "14555d326c66b14967d51a3cb3c8536eafc0d727",
          "md5": "6f0f4a3ef6a655e2ddae128534fe9af6"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android-1.0-debug.aar",
          "url": "url_launcher_android-1.0-debug.aar",
          "size": 15662,
          "sha512": "9fe1c1f40d3c85d12c4ef716132484dd872d653e0ff0a90f2d9fda05492c22d87012d65a3ff666f1bb2f16aff9ef2db88433aa7322a4e6cd661a0b175aca2902",
          "sha256": "9e7cde98eb61d00b350fecf89123610dbd246c23318a695f0eba6422e095b243",
          "sha1": "14555d326c66b14967d51a3cb3c8536eafc0d727",
          "md5": "6f0f4a3ef6a655e2ddae128534fe9af6"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android-1.0-release.aar",
          "url": "url_launcher_android-1.0-release.aar",
          "size": 15027,
          "sha512": "5d7653a73954192edefa1a9bac9954000457bc168274f4358c477769042bd7cfb5c3b3d062819f5a210d3777196f447ef78b19634df48d196561a9c9ddf6290f",
          "sha256": "45e70b13cb55e7cb5be32d7f69b745a0b7e4b1c593d7234c2482a8215e34a4f4",
          "sha1": "50acf5d5a320ffe5e39cc87ae37674a3922883de",
          "md5": "1a6d267c5bce741f7953770642b072ef"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android-1.0-release.aar",
          "url": "url_launcher_android-1.0-release.aar",
          "size": 15027,
          "sha512": "5d7653a73954192edefa1a9bac9954000457bc168274f4358c477769042bd7cfb5c3b3d062819f5a210d3777196f447ef78b19634df48d196561a9c9ddf6290f",
          "sha256": "45e70b13cb55e7cb5be32d7f69b745a0b7e4b1c593d7234c2482a8215e34a4f4",
          "sha1": "50acf5d5a320ffe5e39cc87ae37674a3922883de",
          "md5": "1a6d267c5bce741f7953770642b072ef"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android-1.0-profile.aar",
          "url": "url_launcher_android-1.0-profile.aar",
          "size": 15031,
          "sha512": "8cca3d535a1437c43ec8a4651c5ef8e2c49175bc22cfded05fba00e77d828b556f756ea1ebef8153c6f3aa34fe734c57d0f4bf7d0adc508a988bcf615b62f83a",
          "sha256": "e1c6837aa071b50303a8e586bdab749b3d9a3a99b3ad99b974cc7e9727338bc6",
          "sha1": "cd519da646c6fbd096f09c4b2029089c7fe8c584",
          "md5": "1969ed071e504a45d0bc862b11d9664d"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android-1.0-profile.aar",
          "url": "url_launcher_android-1.0-profile.aar",
          "size": 15031,
          "sha512": "8cca3d535a1437c43ec8a4651c5ef8e2c49175bc22cfded05fba00e77d828b556f756ea1ebef8153c6f3aa34fe734c57d0f4bf7d0adc508a988bcf615b62f83a",
          "sha256": "e1c6837aa071b50303a8e586bdab749b3d9a3a99b3ad99b974cc7e9727338bc6",
          "sha1": "cd519da646c6fbd096f09c4b2029089c7fe8c584",
          "md5": "1969ed071e504a45d0bc862b11d9664d"
        }
      ]
    }
  ]
}
