{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.aar",
          "url": "package_info_plus_debug-1.0.aar",
          "size": 7978,
          "sha512": "9b17450778294c9accabb92f9e95f99e3a9bfe80684764edccfa35f1594ebd27e9eb4807f474e996d13d985a6f7e1fdfbcc7af0f28cd9fa796e4b1d921c310d5",
          "sha256": "0f079f8a0e0c3de49b9f59ef16ec7f6009ae12e7fd1b2c5ebebe7bc7ce6d9a4e",
          "sha1": "715eb199af04401fea8c7b87113c6584c2d8fe92",
          "md5": "2d10349f03df5827e5b2d013a1c23081"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.aar",
          "url": "package_info_plus_debug-1.0.aar",
          "size": 7978,
          "sha512": "9b17450778294c9accabb92f9e95f99e3a9bfe80684764edccfa35f1594ebd27e9eb4807f474e996d13d985a6f7e1fdfbcc7af0f28cd9fa796e4b1d921c310d5",
          "sha256": "0f079f8a0e0c3de49b9f59ef16ec7f6009ae12e7fd1b2c5ebebe7bc7ce6d9a4e",
          "sha1": "715eb199af04401fea8c7b87113c6584c2d8fe92",
          "md5": "2d10349f03df5827e5b2d013a1c23081"
        }
      ]
    }
  ]
}
