{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-debug.aar",
          "url": "device_info_plus-1.0-debug.aar",
          "size": 7067,
          "sha512": "45016debb8a397f4f81730b8e95cd66f17f00b8e32a58fd2f66a377600ef29429ba58f8d94e6d1a66aae31c3ae85e12e17312e1e7dbcc152240546d2ecfad76e",
          "sha256": "08dde9bf1f67673c1749bdf1b1e61ec08e9bc20c58b3644b126a29518d8f96b4",
          "sha1": "9d91f59d006b0c3b242d00ebfd420d6d1a2ad1c2",
          "md5": "641e4eaac5a1a338bbd4ed698442f607"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-debug.aar",
          "url": "device_info_plus-1.0-debug.aar",
          "size": 7067,
          "sha512": "45016debb8a397f4f81730b8e95cd66f17f00b8e32a58fd2f66a377600ef29429ba58f8d94e6d1a66aae31c3ae85e12e17312e1e7dbcc152240546d2ecfad76e",
          "sha256": "08dde9bf1f67673c1749bdf1b1e61ec08e9bc20c58b3644b126a29518d8f96b4",
          "sha1": "9d91f59d006b0c3b242d00ebfd420d6d1a2ad1c2",
          "md5": "641e4eaac5a1a338bbd4ed698442f607"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-release.aar",
          "url": "device_info_plus-1.0-release.aar",
          "size": 6843,
          "sha512": "70a836f262611b516883246f4d450f7d0240e5c4d63b113bba347c0e0130707b24b9ea8f1934ae39f2cffcfcfedd316a11372396d6692dada7796997ed8996c3",
          "sha256": "00a54b892b2776eb44fdbcdc254721a350cbfda8bd9edf2334c8569fa26442f7",
          "sha1": "2038331344b2f5700d330957a4feae39530c0dfa",
          "md5": "9fb464c3063ffdfa5a4c177adf22c34b"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-release.aar",
          "url": "device_info_plus-1.0-release.aar",
          "size": 6843,
          "sha512": "70a836f262611b516883246f4d450f7d0240e5c4d63b113bba347c0e0130707b24b9ea8f1934ae39f2cffcfcfedd316a11372396d6692dada7796997ed8996c3",
          "sha256": "00a54b892b2776eb44fdbcdc254721a350cbfda8bd9edf2334c8569fa26442f7",
          "sha1": "2038331344b2f5700d330957a4feae39530c0dfa",
          "md5": "9fb464c3063ffdfa5a4c177adf22c34b"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-profile.aar",
          "url": "device_info_plus-1.0-profile.aar",
          "size": 6842,
          "sha512": "d5a30944cec200e736ac24001e084334cfc7438ac71fefb2ba18d6aeccc198a4fec05e3527b13073bcd3f2620703f4864a57b6ed18f0b52400c59205823f8080",
          "sha256": "b5cd74f77ad056ad44181360810c8efc962f0a3708aa13c8aa7689c71955f055",
          "sha1": "475cead67b6f346a967c3acc2b77803349b20d3f",
          "md5": "74376f0eea0edf7e3fcf93fbb07dd626"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-profile.aar",
          "url": "device_info_plus-1.0-profile.aar",
          "size": 6842,
          "sha512": "d5a30944cec200e736ac24001e084334cfc7438ac71fefb2ba18d6aeccc198a4fec05e3527b13073bcd3f2620703f4864a57b6ed18f0b52400c59205823f8080",
          "sha256": "b5cd74f77ad056ad44181360810c8efc962f0a3708aa13c8aa7689c71955f055",
          "sha1": "475cead67b6f346a967c3acc2b77803349b20d3f",
          "md5": "74376f0eea0edf7e3fcf93fbb07dd626"
        }
      ]
    }
  ]
}
