{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-debug.aar",
          "url": "device_info_plus-1.0-debug.aar",
          "size": 9656,
          "sha512": "34f03f49e7db3da39008dbc099f75410abf26ec92fccfe1d33f77909ab13fd2ab4ce08496c5054a947b521aad5173b3ff4f1f7aa3287cb838bc6e111fd601d97",
          "sha256": "b376c49ed6d7bd2b27d0833ddd8c0e27190ca7ba4cb40a670e5ab4a9ac1ebbe1",
          "sha1": "6297157911c669b5ceab8848b2e596aae44a95b2",
          "md5": "c242183e55c0d53979c0cb65be4b0f61"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-debug.aar",
          "url": "device_info_plus-1.0-debug.aar",
          "size": 9656,
          "sha512": "34f03f49e7db3da39008dbc099f75410abf26ec92fccfe1d33f77909ab13fd2ab4ce08496c5054a947b521aad5173b3ff4f1f7aa3287cb838bc6e111fd601d97",
          "sha256": "b376c49ed6d7bd2b27d0833ddd8c0e27190ca7ba4cb40a670e5ab4a9ac1ebbe1",
          "sha1": "6297157911c669b5ceab8848b2e596aae44a95b2",
          "md5": "c242183e55c0d53979c0cb65be4b0f61"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-release.aar",
          "url": "device_info_plus-1.0-release.aar",
          "size": 9335,
          "sha512": "575f004516d2698b2f4f3df3ed859bcfbd6976034e209fb7479d65e7a92b5f7617d53142fc1d0464ea4cb3997aef4adfa61dcf9036b954ad8b61c8c1eeb0ed7a",
          "sha256": "349e018cb1ffaae490b2fedcbfd1f82f871b610f9c4edd5548b8a7c6343be542",
          "sha1": "dca8ae1824c005df9c325842bb0f819c5dc3e22b",
          "md5": "423daa910c3b9fda94eb2b5635b41e29"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-release.aar",
          "url": "device_info_plus-1.0-release.aar",
          "size": 9335,
          "sha512": "575f004516d2698b2f4f3df3ed859bcfbd6976034e209fb7479d65e7a92b5f7617d53142fc1d0464ea4cb3997aef4adfa61dcf9036b954ad8b61c8c1eeb0ed7a",
          "sha256": "349e018cb1ffaae490b2fedcbfd1f82f871b610f9c4edd5548b8a7c6343be542",
          "sha1": "dca8ae1824c005df9c325842bb0f819c5dc3e22b",
          "md5": "423daa910c3b9fda94eb2b5635b41e29"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-profile.aar",
          "url": "device_info_plus-1.0-profile.aar",
          "size": 9333,
          "sha512": "a301dfe6dad86f85a337a90cb3c79a7337c65ed7777ae4de8dec54bad68c0717d34224fd4027aa02c0bfddfd6a0a131087a29d05a4ac7a912181ac9937de59d3",
          "sha256": "d312d772681bd2b4b4e740a11b3df4e415f7b0157e959781f37c290d2a0fe373",
          "sha1": "a3cc35ea6cd9a4335293b4630fc72401d629fc53",
          "md5": "00da169b85242c1856e3c2ee73c64583"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus-1.0-profile.aar",
          "url": "device_info_plus-1.0-profile.aar",
          "size": 9333,
          "sha512": "a301dfe6dad86f85a337a90cb3c79a7337c65ed7777ae4de8dec54bad68c0717d34224fd4027aa02c0bfddfd6a0a131087a29d05a4ac7a912181ac9937de59d3",
          "sha256": "d312d772681bd2b4b4e740a11b3df4e415f7b0157e959781f37c290d2a0fe373",
          "sha1": "a3cc35ea6cd9a4335293b4630fc72401d629fc53",
          "md5": "00da169b85242c1856e3c2ee73c64583"
        }
      ]
    }
  ]
}
