{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 8959,
          "sha512": "5ff1f4be6724ef245d1d5803a3a86acc5d4b4c965d64343a64a7a57ac21a6531973e46227105bef50722594d20eea1b70859c9944eceffb81357bd7148491cff",
          "sha256": "ba390112a26727c597ad4c698fc07f2e53d1ad4295b1ee648dc8bf4a0260aa96",
          "sha1": "6045e94da07f425de81ff779fb397534f75423f1",
          "md5": "82c631498273b39c91ea0446d9448d17"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 8959,
          "sha512": "5ff1f4be6724ef245d1d5803a3a86acc5d4b4c965d64343a64a7a57ac21a6531973e46227105bef50722594d20eea1b70859c9944eceffb81357bd7148491cff",
          "sha256": "ba390112a26727c597ad4c698fc07f2e53d1ad4295b1ee648dc8bf4a0260aa96",
          "sha1": "6045e94da07f425de81ff779fb397534f75423f1",
          "md5": "82c631498273b39c91ea0446d9448d17"
        }
      ]
    }
  ]
}
