{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.0.aar",
          "url": "local_auth_android_debug-1.0.aar",
          "size": 51087,
          "sha512": "adf586cb2dfa03eee032518f08321a4f06ebb8774034a78dddea89e784b5c3070c2fb99a5b801591b7da1c3a8a279d311c97e0130daead15eaf94eb77462742f",
          "sha256": "9adb95e4d0737ab2cdcfcda06b6a12ee0eb110afe581cdd37aa4fe4658f533bc",
          "sha1": "51a856c966b9c56adfc7664882ae5a1fe17b9af7",
          "md5": "52a42a1989fa7ccf4d9b158598a3f8e9"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.0.aar",
          "url": "local_auth_android_debug-1.0.aar",
          "size": 51087,
          "sha512": "adf586cb2dfa03eee032518f08321a4f06ebb8774034a78dddea89e784b5c3070c2fb99a5b801591b7da1c3a8a279d311c97e0130daead15eaf94eb77462742f",
          "sha256": "9adb95e4d0737ab2cdcfcda06b6a12ee0eb110afe581cdd37aa4fe4658f533bc",
          "sha1": "51a856c966b9c56adfc7664882ae5a1fe17b9af7",
          "md5": "52a42a1989fa7ccf4d9b158598a3f8e9"
        }
      ]
    }
  ]
}
