{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9656,
          "sha512": "34f03f49e7db3da39008dbc099f75410abf26ec92fccfe1d33f77909ab13fd2ab4ce08496c5054a947b521aad5173b3ff4f1f7aa3287cb838bc6e111fd601d97",
          "sha256": "b376c49ed6d7bd2b27d0833ddd8c0e27190ca7ba4cb40a670e5ab4a9ac1ebbe1",
          "sha1": "6297157911c669b5ceab8848b2e596aae44a95b2",
          "md5": "c242183e55c0d53979c0cb65be4b0f61"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9656,
          "sha512": "34f03f49e7db3da39008dbc099f75410abf26ec92fccfe1d33f77909ab13fd2ab4ce08496c5054a947b521aad5173b3ff4f1f7aa3287cb838bc6e111fd601d97",
          "sha256": "b376c49ed6d7bd2b27d0833ddd8c0e27190ca7ba4cb40a670e5ab4a9ac1ebbe1",
          "sha1": "6297157911c669b5ceab8848b2e596aae44a95b2",
          "md5": "c242183e55c0d53979c0cb65be4b0f61"
        }
      ]
    }
  ]
}
