{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 7067,
          "sha512": "45016debb8a397f4f81730b8e95cd66f17f00b8e32a58fd2f66a377600ef29429ba58f8d94e6d1a66aae31c3ae85e12e17312e1e7dbcc152240546d2ecfad76e",
          "sha256": "08dde9bf1f67673c1749bdf1b1e61ec08e9bc20c58b3644b126a29518d8f96b4",
          "sha1": "9d91f59d006b0c3b242d00ebfd420d6d1a2ad1c2",
          "md5": "641e4eaac5a1a338bbd4ed698442f607"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 7067,
          "sha512": "45016debb8a397f4f81730b8e95cd66f17f00b8e32a58fd2f66a377600ef29429ba58f8d94e6d1a66aae31c3ae85e12e17312e1e7dbcc152240546d2ecfad76e",
          "sha256": "08dde9bf1f67673c1749bdf1b1e61ec08e9bc20c58b3644b126a29518d8f96b4",
          "sha1": "9d91f59d006b0c3b242d00ebfd420d6d1a2ad1c2",
          "md5": "641e4eaac5a1a338bbd4ed698442f607"
        }
      ]
    }
  ]
}
