{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12418,
          "sha512": "d2fe8c7c4964ecc8d0fc74754b52c098de57e1a008b2210f27227c589bc9632d39c2d4921802d00f16e6f3088f91aa7153494cd4d60e9ec5bb084b2a4cd7249b",
          "sha256": "e06dfe7c4e634abb8198e6f18961c58cdd989fa4b29b49561bfac7b7cc9567b7",
          "sha1": "028c374aef38d5364eef0bb56631c2664e158885",
          "md5": "d8ae0e55b4ed99127a0545c1e628d5d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12418,
          "sha512": "d2fe8c7c4964ecc8d0fc74754b52c098de57e1a008b2210f27227c589bc9632d39c2d4921802d00f16e6f3088f91aa7153494cd4d60e9ec5bb084b2a4cd7249b",
          "sha256": "e06dfe7c4e634abb8198e6f18961c58cdd989fa4b29b49561bfac7b7cc9567b7",
          "sha1": "028c374aef38d5364eef0bb56631c2664e158885",
          "md5": "d8ae0e55b4ed99127a0545c1e628d5d5"
        }
      ]
    }
  ]
}
