{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12402,
          "sha512": "07897c816d5716a748bf1b38883bd36ed31ee48775c6add8e56f04825afd2dccbd16046434dfac98804798dcd2aac0e8893049961c28ccaaaacb7ff46871afae",
          "sha256": "a98783c8cb8b89adc2f040562a95aced0c5bec0c6c3498f40cc512400b26169b",
          "sha1": "3b51416a9a15e804140781d999a1e1b2628651b1",
          "md5": "a44f49a400e745e0217349a0fd25bff3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12402,
          "sha512": "07897c816d5716a748bf1b38883bd36ed31ee48775c6add8e56f04825afd2dccbd16046434dfac98804798dcd2aac0e8893049961c28ccaaaacb7ff46871afae",
          "sha256": "a98783c8cb8b89adc2f040562a95aced0c5bec0c6c3498f40cc512400b26169b",
          "sha1": "3b51416a9a15e804140781d999a1e1b2628651b1",
          "md5": "a44f49a400e745e0217349a0fd25bff3"
        }
      ]
    }
  ]
}
