{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_safe",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe-1.0-debug.aar",
          "url": "open_file_safe-1.0-debug.aar",
          "size": 14321,
          "sha512": "10ae766c67c517bb93e7c13a3c572a2ce241eb289e741ba87bfa6f8b382d288b9df83969c67703fa62686fcaed48499a4c54c36365c4972dcbe61f0a67206280",
          "sha256": "0b187708114a7ffeaca310d270a5fba38a02128a0542df825cb653f11669c8fa",
          "sha1": "6c77f273db34c3b9eead8c32bcbb82ba62c1c4f2",
          "md5": "aee73536955e1d2958b0512c808bc032"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe-1.0-debug.aar",
          "url": "open_file_safe-1.0-debug.aar",
          "size": 14321,
          "sha512": "10ae766c67c517bb93e7c13a3c572a2ce241eb289e741ba87bfa6f8b382d288b9df83969c67703fa62686fcaed48499a4c54c36365c4972dcbe61f0a67206280",
          "sha256": "0b187708114a7ffeaca310d270a5fba38a02128a0542df825cb653f11669c8fa",
          "sha1": "6c77f273db34c3b9eead8c32bcbb82ba62c1c4f2",
          "md5": "aee73536955e1d2958b0512c808bc032"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe-1.0-release.aar",
          "url": "open_file_safe-1.0-release.aar",
          "size": 13755,
          "sha512": "6782e2e505e9e6fd586b21c0622e79119081f2bb85f9e7316a4127c18849cbf3220b3cc048447e8976e4b6bd55f3338719b641e04f4163277e5b1349f4473bbc",
          "sha256": "40f6ce4c6f5385fe3bc81c142132d2ba4e4db6b5cd2d8b0cc87043d00f6b583e",
          "sha1": "3ed9f7adb48f413089216c5c3c9769e4388f4518",
          "md5": "0300aea786efa1c0162f67fcb1381d62"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe-1.0-release.aar",
          "url": "open_file_safe-1.0-release.aar",
          "size": 13755,
          "sha512": "6782e2e505e9e6fd586b21c0622e79119081f2bb85f9e7316a4127c18849cbf3220b3cc048447e8976e4b6bd55f3338719b641e04f4163277e5b1349f4473bbc",
          "sha256": "40f6ce4c6f5385fe3bc81c142132d2ba4e4db6b5cd2d8b0cc87043d00f6b583e",
          "sha1": "3ed9f7adb48f413089216c5c3c9769e4388f4518",
          "md5": "0300aea786efa1c0162f67fcb1381d62"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe-1.0-profile.aar",
          "url": "open_file_safe-1.0-profile.aar",
          "size": 13753,
          "sha512": "6942f3eb706766a25d586709d0ab237c4110ffcd4fe0a2e7b2ee0f622df4e84d8ed672300237f5bd1f3ce609e535e9a7f874d1c885cb41bdf60e90b23a2188ff",
          "sha256": "73cad81936fccfd9492e5f4a5d0bf200752b5e8a0091bf9de82988d452e607a0",
          "sha1": "dc785cf888d3336d33e126daf0e2dd4a6263e416",
          "md5": "039c141a3cb6b6d6b83b7bc9b2158096"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe-1.0-profile.aar",
          "url": "open_file_safe-1.0-profile.aar",
          "size": 13753,
          "sha512": "6942f3eb706766a25d586709d0ab237c4110ffcd4fe0a2e7b2ee0f622df4e84d8ed672300237f5bd1f3ce609e535e9a7f874d1c885cb41bdf60e90b23a2188ff",
          "sha256": "73cad81936fccfd9492e5f4a5d0bf200752b5e8a0091bf9de82988d452e607a0",
          "sha1": "dc785cf888d3336d33e126daf0e2dd4a6263e416",
          "md5": "039c141a3cb6b6d6b83b7bc9b2158096"
        }
      ]
    }
  ]
}
