{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7614,
          "sha512": "880f8b27d8ab81053d62c8452e92ef7eced0b7ae8ecb83ae25f85004a8beab9cb4a3453a719a28ac59e8e9bdecec7dfbed77596ea875e1720eda0aee0bd77031",
          "sha256": "ee4d1f01416d70c88d7733e680e5e4493a293f292fd90fc3e46da4648c41b56b",
          "sha1": "c36a6a3c2898403538e0e97ff91f62b6537bb1d6",
          "md5": "22f9789ab63a10e52a6391702ef5faf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7614,
          "sha512": "880f8b27d8ab81053d62c8452e92ef7eced0b7ae8ecb83ae25f85004a8beab9cb4a3453a719a28ac59e8e9bdecec7dfbed77596ea875e1720eda0aee0bd77031",
          "sha256": "ee4d1f01416d70c88d7733e680e5e4493a293f292fd90fc3e46da4648c41b56b",
          "sha1": "c36a6a3c2898403538e0e97ff91f62b6537bb1d6",
          "md5": "22f9789ab63a10e52a6391702ef5faf1"
        }
      ]
    }
  ]
}
