{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7680,
          "sha512": "75bf053d1ec611f0b84ec708d494e2c38dd1172347859c2b2556abb8191c1ababfabd7c0d071a98657a619a9bd05dffcc41fa576c897648f23648bd3d442f088",
          "sha256": "7846302c373f0c09c0013a0421cc686cc4aba1cd58f12e48267861d8a1f385ad",
          "sha1": "7bfbca8a79024f6cd5ba3ed342024dd10297a10d",
          "md5": "488502c301a2f47ef018e1821561729c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7680,
          "sha512": "75bf053d1ec611f0b84ec708d494e2c38dd1172347859c2b2556abb8191c1ababfabd7c0d071a98657a619a9bd05dffcc41fa576c897648f23648bd3d442f088",
          "sha256": "7846302c373f0c09c0013a0421cc686cc4aba1cd58f12e48267861d8a1f385ad",
          "sha1": "7bfbca8a79024f6cd5ba3ed342024dd10297a10d",
          "md5": "488502c301a2f47ef018e1821561729c"
        }
      ]
    }
  ]
}
