{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_profile-1.0.aar",
          "url": "package_info_plus_profile-1.0.aar",
          "size": 7613,
          "sha512": "72a1163a323596b34c01552629c8d7477f5b0bda0bec06fa13830355f2aedf525581b4a7b3b8e03194513d3b73052ff0355da76cdb771db3331b41317a86cb31",
          "sha256": "610889bd154630f0d6a60471bbd6fa3afd85fa8a54ee700fb31cd5a43a16545c",
          "sha1": "5acd2d1d14883cc782aa09513a32ecb3f2b93ee1",
          "md5": "06a652aff9d931c4030df2bee5546278"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_profile-1.0.aar",
          "url": "package_info_plus_profile-1.0.aar",
          "size": 7613,
          "sha512": "72a1163a323596b34c01552629c8d7477f5b0bda0bec06fa13830355f2aedf525581b4a7b3b8e03194513d3b73052ff0355da76cdb771db3331b41317a86cb31",
          "sha256": "610889bd154630f0d6a60471bbd6fa3afd85fa8a54ee700fb31cd5a43a16545c",
          "sha1": "5acd2d1d14883cc782aa09513a32ecb3f2b93ee1",
          "md5": "06a652aff9d931c4030df2bee5546278"
        }
      ]
    }
  ]
}
