{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_profile-1.0.aar",
          "url": "package_info_plus_profile-1.0.aar",
          "size": 7676,
          "sha512": "5281dc194071b6d28cd41a55c507b2a0637b9d02fec0fda4475089b72c2f7eb779aacccc518c00bed28b213acdee81ffeea80ccdc2694a66b88bd6bb5b2b591b",
          "sha256": "85fee7285c7fd2cade21848ce10f510671d15f4748d46a0942b8d9545efa0524",
          "sha1": "0003b655d7aaf204e62b75a0ac53282b93efa908",
          "md5": "3ba82efce289813e8d7c2649049c62e1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_profile-1.0.aar",
          "url": "package_info_plus_profile-1.0.aar",
          "size": 7676,
          "sha512": "5281dc194071b6d28cd41a55c507b2a0637b9d02fec0fda4475089b72c2f7eb779aacccc518c00bed28b213acdee81ffeea80ccdc2694a66b88bd6bb5b2b591b",
          "sha256": "85fee7285c7fd2cade21848ce10f510671d15f4748d46a0942b8d9545efa0524",
          "sha1": "0003b655d7aaf204e62b75a0ac53282b93efa908",
          "md5": "3ba82efce289813e8d7c2649049c62e1"
        }
      ]
    }
  ]
}
